---
title: "R Notebook"
output: html_notebook
---

```{r}
if (dir.exists("C:/Users/usuario/Desktop/TRMM-Calibration/Data")) {
  dir <- "C:/Users/usuario/Desktop/TRMM-Calibration/Data"
}else{
  dir <- "/vols/seal/oceano/gmeteo/WORK/juaco/trmm/clustering"
}
```

```{r setup}
knitr::opts_knit$set(root.dir = dir)
```

```{r}
library(downscaleR)
library(visualizeR)
library(convertR)
library(magrittr)
library(evd)
library(raster)
library(rasterVis)
library(sp)
library(grid)
library(RColorBrewer)
library(lubridate)
library(scales)
```

```{r}
load("pca.RData")
load("pp_reanalysis.RData")
```

```{r}
k = 5
load('kmModel5.RData')
```

```{r}
idx.tp <- which(attributes(pca$tp[[1]])$explained_variance >= .75)[1]
idx.msl <- which(attributes(pca$msl[[1]])$explained_variance >= .9)[1]
idx.diff.msl <- which(attributes(pca$diff_msl[[1]])$explained_variance >= .9)[1]

pca.matrix <- cbind(pca$tp[[1]]$PCs[,1:idx.tp],pca$msl[[1]]$PCs[,1:idx.msl],pca$diff_msl[[1]]$PCs[,1:idx.diff.msl])
```


```{r}
cyclones <- read.csv('C:/Users/usuario/Desktop/Master/tfm/Notebooks_TFM/SP_cyclones_time_series_1998_2020.csv')
cyclones$Date <- as.Date(cyclones$Date)
cyclones <- cyclones[,2:3]

```

```{r}
lista <- lapply(1:k, function(x) subsetDimension(pp_reanalysis, dimension = "time", indices = which(kmModel5$cluster == x)) %>% climatology())

kmedias.pp <- bindGrid(lista, dimension = "member", skip.temporal.check = TRUE)

spatialPlot(kmedias.pp,backdrop.theme = 'countries', rev.color = T, as.table = T,colorkey = list(space ="bottom",height=1, width=1), color.theme = 'Spectral', names.attr = paste("Days in cluster", 1:k, ":",kmModel5$size[1:k]))
```


```{r}
x <- seq(1,365)
y <- seq(1998,2020)

data <- expand.grid(X=x, Y=y)
data$Z <- as.vector(matrix(kmModel5$cluster, nrow = 23,ncol = 365))

data$Z <- as.character(data$Z)

levelplot(Z ~ X*Y, data=data  ,xlab="Season", ylab = "Years",scales=list(x=list(at=NULL)),
          main="", col.regions =  c("#006837","#66C2A5","#FFFFBF","#5E4FA2","#F46D43"), at = 0:5)

grid.text("Feb", .18, .13, gp = gpar(cex = .8) )
grid.text("Mar", .24, .13, gp = gpar(cex = .8) )
grid.text("Apr", .3, .13, gp = gpar(cex = .8) )
grid.text("May", .37, .13, gp = gpar(cex = .8) )
grid.text("Jun", .435, .13, gp = gpar(cex = .8) )
grid.text("Jul", .495, .13, gp = gpar(cex = .8) )
grid.text("Aug", .56, .13, gp = gpar(cex = .8) )
grid.text("Sep", .63, .13, gp = gpar(cex = .8) )
grid.text("Oct", .69, .13, gp = gpar(cex = .8) )
grid.text("Nov", .76, .13, gp = gpar(cex = .8) )
grid.text("Dec", .82, .13, gp = gpar(cex = .8) )
```

```{r}
cyc.data <- expand.grid(X=x, Y=y)
cyc.data$Z <- as.vector(matrix(cyclones$cyclones_generation_centers, nrow = 23,ncol = 365))
```

```{r}
idx <- which(cyc.data$Z > 0)
cyc.data$Z[idx] = 1
coordinates(cyc.data) <- ~ X+Y
```




```{r}
levelplot(Z ~ X*Y, data=data  ,xlab="Season", ylab = "Years", scales=list(x=list(at=NULL)),
          main="", col.regions = c("#006837","#66C2A5","#FFFFBF","#5E4FA2","#F46D43"), at = 0:5) +
  layer(sp.points(cyc.data, pch = 21, cex = cyc.data$Z/50, col = 'white'))

grid.text("Feb", .18, .13, gp = gpar(cex = .8) )
grid.text("Mar", .24, .13, gp = gpar(cex = .8) )
grid.text("Apr", .3, .13, gp = gpar(cex = .8) )
grid.text("May", .37, .13, gp = gpar(cex = .8) )
grid.text("Jun", .435, .13, gp = gpar(cex = .8) )
grid.text("Jul", .495, .13, gp = gpar(cex = .8) )
grid.text("Aug", .56, .13, gp = gpar(cex = .8) )
grid.text("Sep", .63, .13, gp = gpar(cex = .8) )
grid.text("Oct", .69, .13, gp = gpar(cex = .8) )
grid.text("Nov", .76, .13, gp = gpar(cex = .8) )
grid.text("Dec", .82, .13, gp = gpar(cex = .8) )
```

```{r}
levelplot(Z ~ X*Y, data=data  ,xlab="Days", ylab = "Years", scales=list(x=list(at=NULL)),
          main="", col.regions = c("#006837","#66C2A5","#FFFFBF","#5E4FA2","#F46D43"), at = 0:5) +
  layer(sp.points(cyc.data, pch = 21, cex = cyc.data$Z/50, col = 'white'))+
  layer(panel.segments(31,1997.5,31,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(59,1997.5,59,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(90,1997.5,90,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(120,1997.5,120,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(151,1997.5,151,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(181,1997.5,181,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(212,1997.5,212,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(243,1997.5,243,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(273,1997.5,273,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(304,1997.5,304,2020.5, col = 'lavender', lwd =2))+
  layer(panel.segments(334,1997.5,334,2020.5, col = 'lavender', lwd =2))

grid.text("Feb", .18, .13, gp = gpar(cex = .8) )
grid.text("Mar", .24, .13, gp = gpar(cex = .8) )
grid.text("Apr", .3, .13, gp = gpar(cex = .8) )
grid.text("May", .37, .13, gp = gpar(cex = .8) )
grid.text("Jun", .435, .13, gp = gpar(cex = .8) )
grid.text("Jul", .495, .13, gp = gpar(cex = .8) )
grid.text("Aug", .56, .13, gp = gpar(cex = .8) )
grid.text("Sep", .63, .13, gp = gpar(cex = .8) )
grid.text("Oct", .69, .13, gp = gpar(cex = .8) )
grid.text("Nov", .76, .13, gp = gpar(cex = .8) )
grid.text("Dec", .82, .13, gp = gpar(cex = .8) )
```

```{r}
load("C:/Users/usuario/Desktop/TRMM-Calibration/Data/slp.RData")

```

```{r}
cl1.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 1)

cl1.slp.apia <- subsetGrid(cl1.slp, lonLim = cl1.slp$xyCoords$x[which.min(abs(cl1.slp$xyCoords$x-(-171.7666636)))], latLim = cl1.slp$xyCoords$y[which.min(abs(cl1.slp$xyCoords$y-(-13.83333)))])
cl1.slp.suva <- subsetGrid(cl1.slp, lonLim = cl1.slp$xyCoords$x[which.min(abs(cl1.slp$xyCoords$x-(178.44149)))], latLim = cl1.slp$xyCoords$y[which.min(abs(cl1.slp$xyCoords$y-(-18.1416)))])
cl1.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 1)

cl1.spi <- scale(cl1.slp.suva$Data - cl1.slp.apia$Data)

```


```{r}
cl2.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 2)

cl2.slp.apia <- subsetGrid(cl2.slp, lonLim = cl2.slp$xyCoords$x[which.min(abs(cl2.slp$xyCoords$x-(-171.7666636)))], latLim = cl2.slp$xyCoords$y[which.min(abs(cl2.slp$xyCoords$y-(-13.83333)))])
cl2.slp.suva <- subsetGrid(cl2.slp, lonLim = cl2.slp$xyCoords$x[which.min(abs(cl2.slp$xyCoords$x-(178.44149)))], latLim = cl2.slp$xyCoords$y[which.min(abs(cl2.slp$xyCoords$y-(-18.1416)))])
cl2.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 2)

cl2.spi <- scale(cl2.slp.suva$Data - cl2.slp.apia$Data)

```

```{r}
cl3.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 3)

cl3.slp.apia <- subsetGrid(cl3.slp, lonLim = cl3.slp$xyCoords$x[which.min(abs(cl3.slp$xyCoords$x-(-171.7666636)))], latLim = cl3.slp$xyCoords$y[which.min(abs(cl3.slp$xyCoords$y-(-13.83333)))])
cl3.slp.suva <- subsetGrid(cl3.slp, lonLim = cl3.slp$xyCoords$x[which.min(abs(cl3.slp$xyCoords$x-(178.44149)))], latLim = cl3.slp$xyCoords$y[which.min(abs(cl3.slp$xyCoords$y-(-18.1416)))])
cl3.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 3)

cl3.spi <- scale(cl3.slp.suva$Data - cl3.slp.apia$Data)

```

```{r}
cl4.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 4)

cl4.slp.apia <- subsetGrid(cl4.slp, lonLim = cl4.slp$xyCoords$x[which.min(abs(cl4.slp$xyCoords$x-(-171.7666636)))], latLim = cl4.slp$xyCoords$y[which.min(abs(cl4.slp$xyCoords$y-(-13.83333)))])
cl4.slp.suva <- subsetGrid(cl4.slp, lonLim = cl4.slp$xyCoords$x[which.min(abs(cl4.slp$xyCoords$x-(178.44149)))], latLim = cl4.slp$xyCoords$y[which.min(abs(cl4.slp$xyCoords$y-(-18.1416)))])
cl4.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 4)

cl4.spi <- scale(cl4.slp.suva$Data - cl4.slp.apia$Data)

```

```{r}
cl5.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 5)

cl5.slp.apia <- subsetGrid(cl5.slp, lonLim = cl5.slp$xyCoords$x[which.min(abs(cl5.slp$xyCoords$x-(-171.7666636)))], latLim = cl5.slp$xyCoords$y[which.min(abs(cl5.slp$xyCoords$y-(-13.83333)))])
cl5.slp.suva <- subsetGrid(cl5.slp, lonLim = cl5.slp$xyCoords$x[which.min(abs(cl5.slp$xyCoords$x-(178.44149)))], latLim = cl5.slp$xyCoords$y[which.min(abs(cl5.slp$xyCoords$y-(-18.1416)))])
cl5.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 5)

cl5.spi <- scale(cl5.slp.suva$Data - cl5.slp.apia$Data)

```


```{r}
count.cl1 <- 1
count.cl2 <- 1
count.cl3 <- 1
count.cl4 <- 1
count.cl5 <- 1
for (i in c(1:length(kmModel5$cluster))) {
  if (kmModel5$cluster[i] == 1) {
    if (cl1.spi[count.cl1] < 0) {
    
      kmModel5$cluster[i] <- 1
    
    }else if(cl1.spi[count.cl1] >0){
    
      kmModel5$cluster[i] <- 1.5
    
    }
    
    count.cl1 <- count.cl1 +1
  
  }else if(kmModel5$cluster[i] == 2){
    if (cl2.spi[count.cl2] < 0) {
    
      kmModel5$cluster[i] <- 2
    
    }else if(cl2.spi[count.cl2] >0){
    
      kmModel5$cluster[i] <- 2.5
    
    }
    
    count.cl2 <- count.cl2 +1
    
  }else if(kmModel5$cluster[i] == 3){
    if (cl3.spi[count.cl3] < 0) {
    
      kmModel5$cluster[i] <- 3
    
    }else if(cl3.spi[count.cl3] >0){
    
      kmModel5$cluster[i] <-3.5
    
    }
    
    count.cl3 <- count.cl3 +1
    
  }else if(kmModel5$cluster[i] == 4){
    if (cl4.spi[count.cl4] < 0) {
    
      kmModel5$cluster[i] <- 4
    
    }else if(cl4.spi[count.cl4] >0){
    
      kmModel5$cluster[i] <- 4.5
    
    }
    
    count.cl4 <- count.cl4 +1
    
  }else{
    if (cl5.spi[count.cl5] < 0) {
    
      kmModel5$cluster[i] <- 5
    
    }else if(cl5.spi[count.cl5] >0){
    
      kmModel5$cluster[i] <- 5.5
    
    }
    
    count.cl5 <- count.cl5 +1
    
  }
}
```

```{r}
x <- seq(1,365)
y <- seq(1998,2020)

data <- expand.grid(X=x, Y=y)
data$Z <- as.vector(matrix(kmModel5$cluster, nrow = 23,ncol = 365))


levelplot(Z ~ X*Y, data=data  ,xlab="Season", ylab = "Years",scales=list(x=list(at=NULL)),
          main="", col.regions = c(alpha("#1F78B4", alpha = 1), alpha("#1F78B4", alpha = .5),alpha("#33A02C", alpha = 1), alpha("#33A02C", alpha = .5),alpha("#B15928", alpha = 1),alpha("#B15928", alpha = .5),alpha("#6A3D9A", alpha = 1),alpha("#6A3D9A", alpha = .5),alpha("#FFFF99", alpha = 1),alpha("#FFFF99", alpha = .25)),at = seq(.5,5.5,.5))

grid.text("Feb", .18, .13, gp = gpar(cex = .8) )
grid.text("Mar", .24, .13, gp = gpar(cex = .8) )
grid.text("Apr", .3, .13, gp = gpar(cex = .8) )
grid.text("May", .37, .13, gp = gpar(cex = .8) )
grid.text("Jun", .435, .13, gp = gpar(cex = .8) )
grid.text("Jul", .495, .13, gp = gpar(cex = .8) )
grid.text("Aug", .56, .13, gp = gpar(cex = .8) )
grid.text("Sep", .63, .13, gp = gpar(cex = .8) )
grid.text("Oct", .69, .13, gp = gpar(cex = .8) )
grid.text("Nov", .76, .13, gp = gpar(cex = .8) )
grid.text("Dec", .82, .13, gp = gpar(cex = .8) )

grid.text("-", .98, .2, gp = gpar(cex = 2))
grid.text("+", .98, .28, gp = gpar(cex = 1.5))

grid.text("-", .98, .35, gp = gpar(cex = 2))
grid.text("+", .98, .43, gp = gpar(cex = 1.5))

grid.text("-", .98, .5, gp = gpar(cex = 2))
grid.text("+", .98, .57, gp = gpar(cex = 1.5))

grid.text("-", .98, .64, gp = gpar(cex = 2))
grid.text("+", .98, .71, gp = gpar(cex = 1.5))

grid.text("-", .98, .78, gp = gpar(cex = 2))
grid.text("+", .98, .86, gp = gpar(cex = 1.5))
```

```{r}
x <- seq(1,365)
y <- seq(1998,2020)

data <- expand.grid(X=x, Y=y)
data$Z <- as.vector(matrix(kmModel5$cluster, nrow = 23,ncol = 365))


levelplot(Z ~ X*Y, data=data  ,xlab="Season", ylab = "Years",scales=list(x=list(at=NULL)),
          main="", col.regions = c(alpha("#1F78B4", alpha = 1), alpha("#1F78B4", alpha = .5),alpha("#33A02C", alpha = 1), alpha("#33A02C", alpha = .5),alpha("#B15928", alpha = 1),alpha("#B15928", alpha = .5),alpha("#6A3D9A", alpha = 1),alpha("#6A3D9A", alpha = .5),alpha("#FFFF99", alpha = 1),alpha("#FFFF99", alpha = .25)),at = seq(.5,5.5,.5)) +
  layer(sp.points(cyc.data, pch = 21, cex = cyc.data$Z/50, col = 'black'))

grid.text("Feb", .18, .13, gp = gpar(cex = .8) )
grid.text("Mar", .24, .13, gp = gpar(cex = .8) )
grid.text("Apr", .3, .13, gp = gpar(cex = .8) )
grid.text("May", .37, .13, gp = gpar(cex = .8) )
grid.text("Jun", .435, .13, gp = gpar(cex = .8) )
grid.text("Jul", .495, .13, gp = gpar(cex = .8) )
grid.text("Aug", .56, .13, gp = gpar(cex = .8) )
grid.text("Sep", .63, .13, gp = gpar(cex = .8) )
grid.text("Oct", .69, .13, gp = gpar(cex = .8) )
grid.text("Nov", .76, .13, gp = gpar(cex = .8) )
grid.text("Dec", .82, .13, gp = gpar(cex = .8) )

grid.text("-", .98, .2, gp = gpar(cex = 2))
grid.text("+", .98, .28, gp = gpar(cex = 1.5))

grid.text("-", .98, .35, gp = gpar(cex = 2))
grid.text("+", .98, .43, gp = gpar(cex = 1.5))

grid.text("-", .98, .5, gp = gpar(cex = 2))
grid.text("+", .98, .57, gp = gpar(cex = 1.5))

grid.text("-", .98, .64, gp = gpar(cex = 2))
grid.text("+", .98, .71, gp = gpar(cex = 1.5))

grid.text("-", .98, .78, gp = gpar(cex = 2))
grid.text("+", .98, .86, gp = gpar(cex = 1.5))

grid.text("WT & SPI", .95, .13, gp = gpar(cex = .8))
grid.text("phase", .95, .1, gp = gpar(cex = .8))

```

```{r}
vTert = quantile(cl1.spi, c(0:3/3))

# classify values
tert = cut(cl1.spi, 
                   vTert, 
                   include.lowest = T, 
                   labels = c("Negative", "Neutral", "Positive"))

df1 <- data.frame(cl1.spi, tert)

```

```{r}
vTert = quantile(cl2.spi, c(0:3/3))

# classify values
tert = cut(cl2.spi, 
                   vTert, 
                   include.lowest = T, 
                   labels = c("Negative", "Neutral", "Positive"))

df2 <- data.frame(cl2.spi, tert)

vTert = quantile(cl3.spi, c(0:3/3))

# classify values
tert = cut(cl3.spi, 
                   vTert, 
                   include.lowest = T, 
                   labels = c("Negative", "Neutral", "Positive"))

df3<- data.frame(cl3.spi, tert)

vTert = quantile(cl4.spi, c(0:3/3))

# classify values
tert = cut(cl4.spi, 
                   vTert, 
                   include.lowest = T, 
                   labels = c("Negative", "Neutral", "Positive"))

df4 <- data.frame(cl4.spi, tert)

vTert = quantile(cl5.spi, c(0:3/3))

# classify values
tert = cut(cl5.spi, 
                   vTert, 
                   include.lowest = T, 
                   labels = c("Negative", "Neutral", "Positive"))

df5 <- data.frame(cl5.spi, tert)
```

```{r}
count.cl1 <- 1
count.cl2 <- 1
count.cl3 <- 1
count.cl4 <- 1
count.cl5 <- 1

load('C:/Users/usuario/Desktop/TRMM-Calibration/Data/kmModel5.RData')

for (i in c(1:length(kmModel5$cluster))) {
  if (kmModel5$cluster[i] == 1) {
    if (df1$tert[count.cl1] == "Negative") {
    
      kmModel5$cluster[i] <- 1
    
    }else if(df1$tert[count.cl1] == "Positive"){
    
      kmModel5$cluster[i] <- 1.6
    
    }else{
      kmModel5$cluster[i] <- 1.3
    }
    
    count.cl1 <- count.cl1 +1
  
  }else if(kmModel5$cluster[i] == 2){
    if (df2$tert[count.cl2] == "Negative") {
    
      kmModel5$cluster[i] <- 2
    
    }else if(df2$tert[count.cl2] == "Positive"){
    
      kmModel5$cluster[i] <- 2.6
    
    }else{
      kmModel5$cluster[i] <- 2.3
    }
    
    count.cl2 <- count.cl2 +1
    
  }else if(kmModel5$cluster[i] == 3){
    if (df3$tert[count.cl3] == "Negative") {
    
      kmModel5$cluster[i] <- 3
    
    }else if(df3$tert[count.cl3] == "Positive"){
    
      kmModel5$cluster[i] <- 3.6
    
    }else{
      kmModel5$cluster[i] <- 3.3
    }
    
    count.cl3 <- count.cl3 +1
    
  }else if(kmModel5$cluster[i] == 4){
    if (df4$tert[count.cl4] == "Negative") {
    
      kmModel5$cluster[i] <- 4
    
    }else if(df4$tert[count.cl4] == "Positive"){
    
      kmModel5$cluster[i] <- 4.6
    
    }else{
      kmModel5$cluster[i] <- 4.3
    }
    
    count.cl4 <- count.cl4 +1
    
  }else{
    if (df5$tert[count.cl5] == "Negative") {
    
      kmModel5$cluster[i] <- 5
    
    }else if(df5$tert[count.cl5] == "Positive"){
    
      kmModel5$cluster[i] <- 5.6
    
    }else{
      kmModel5$cluster[i] <- 5.3
    }
    
    count.cl5 <- count.cl5 +1
    
  }
}
```

```{r}
x <- seq(1,365)
y <- seq(1998,2020)

data <- expand.grid(X=x, Y=y)
data$Z <- as.vector(matrix(kmModel5$cluster, nrow = 23,ncol = 365))


levelplot(Z ~ X*Y, data=data  ,xlab="Season", ylab = "Years",scales=list(x=list(at=NULL)),
          main="", col.regions = c(alpha("#006837", alpha = 1),alpha("#006837", alpha = .5) ,alpha("#006837", alpha = .25),alpha("#3288BD", alpha = 1), alpha("#3288BD", alpha = .5),alpha("#3288BD", alpha = .25),alpha("#FFFFBF", alpha = 1),alpha("#FFFFBF", alpha = .5),alpha("#FFFFBF", alpha = .25),alpha("#5E4FA2", alpha = 1),alpha("#5E4FA2", alpha = .5),alpha("#5E4FA2", alpha = .25),alpha("#F46D43", alpha = 1),alpha("#F46D43", alpha = .5),alpha("#F46D43", alpha = .25)),at = sort(unique(kmModel5$cluster)))

grid.text("Feb", .18, .13, gp = gpar(cex = .8) )
grid.text("Mar", .24, .13, gp = gpar(cex = .8) )
grid.text("Apr", .3, .13, gp = gpar(cex = .8) )
grid.text("May", .37, .13, gp = gpar(cex = .8) )
grid.text("Jun", .435, .13, gp = gpar(cex = .8) )
grid.text("Jul", .495, .13, gp = gpar(cex = .8) )
grid.text("Aug", .56, .13, gp = gpar(cex = .8) )
grid.text("Sep", .63, .13, gp = gpar(cex = .8) )
grid.text("Oct", .69, .13, gp = gpar(cex = .8) )
grid.text("Nov", .76, .13, gp = gpar(cex = .8) )
grid.text("Dec", .82, .13, gp = gpar(cex = .8) )
```

