---
title: "Ranking Index without calibration conditioned to WT"
output: html_notebook
---

    
```{r}
library(loadeR)
library(transformeR)
library(downscaleR)
library(visualizeR)
library(convertR)
library(ncdf4)
library(climate4R.value)
library(magrittr)
library(evd)
library(formattable) #neccessary to create tables with colors
library(lubridate) #neccessary to calculate differences in years between dates
library(lattice)
library(ggplot2)
library(raster)
library(rasterVis)
library(sp)

if (dir.exists("C:/Users/usuario/Desktop/TRMM-Calibration/Data")) {
  dir <- "C:/Users/usuario/Desktop/TRMM-Calibration/Data"
}else{
  dir <- "/vols/abedul/meteo/mironeso/trmm"
}

```

```{r setup}
knitr::opts_knit$set(root.dir = dir)
```

```{r}
set.seed(42)

load("pca.RData")
load("pp_reanalysis.RData")
idx.tp <- which(attributes(pca$tp[[1]])$explained_variance >= .75)[1]
idx.msl <- which(attributes(pca$msl[[1]])$explained_variance >= .9)[1]
idx.diff.msl <- which(attributes(pca$diff_msl[[1]])$explained_variance >= .9)[1]

pca.matrix <- cbind(pca$tp[[1]]$PCs[,1:idx.tp],pca$msl[[1]]$PCs[,1:idx.msl],pca$diff_msl[[1]]$PCs[,1:idx.diff.msl])

k = 5
load('C:/Users/usuario/Desktop/TRMM-Calibration/Data/kmModel5.RData')

kmModel5$cluster <- kmModel5$cluster[1:8034]
precip_obs <- loadStationData("C:/Users/usuario/Desktop/TRMM-Calibration/TRMM-time-series/WT_Analysis_Calibration/SP_ascii.zip", var = "precip_obs")
precip_trmm <- loadStationData("C:/Users/usuario/Desktop/TRMM-Calibration/TRMM-time-series/WT_Analysis_Calibration/SP_ascii.zip", var = "precip_trmm")

```
```{r}
lista <- lapply(1:k, function(x) subsetDimension(pp_reanalysis, dimension = "time", indices = which(kmModel5$cluster == x)) %>% climatology())
kmedias.pp <- bindGrid(lista, dimension = "member", skip.temporal.check = TRUE)

spatialPlot(kmedias.pp,backdrop.theme = 'countries', rev.color = T, as.table = T, names.attr = paste("Days in cluster", 1:k, ":",kmModel5$size[1:k]))

```
```{r}
kmModel5$cluster <- kmModel5$cluster[1:8034]

```

```{r}
MaxReturnValue <- function(data){
  #library(lubridate)
  #nyears <- round(time_length(difftime(cal.madrid.eqm$Dates$end[length(cal.madrid.eqm$Dates$end)], cal.madrid.eqm$Dates$start[1]),"years"))
  nyears <- 20
  data.maxYear <- aggregateGrid(redim(data), aggr.y = list(FUN = "max",na.rm = TRUE))

  data.maxrv <- climatology(data, clim.fun = list(FUN = "mean", na.rm = T))

  auxData <- data.maxYear$Data
  auxData[which(is.infinite(auxData))] <- NA

  if (any(!is.na(auxData))){
      auxGEV <- fgev(auxData)
      if ((auxGEV$estimate[3] - auxGEV$std.err[3] < 0) & (0  < auxGEV$estimate[3] + auxGEV$std.err[3])){
        auxGEV <- fgev(auxData, shape = 0)
        auxRV <- qgev(1-1/nyears, loc = auxGEV$estimate[1], scale = auxGEV$estimate[2], shape = 0)
      }else{
        auxRV <- qgev(1-1/nyears, loc = auxGEV$estimate[1], scale = auxGEV$estimate[2], shape = auxGEV$estimate[3])
      }
      data.maxrv <- as.numeric(auxRV)
      names(data.maxrv) <- paste("RV",nyears,"_max", sep = "")
  }
  return(data.maxrv)
  }
```

```{r}
pp_reanalysis <- subsetGrid(pp_reanalysis, years = 1998:2019)
```

# Non-Conditioned to WT

## Wallis y Futuna
```{r}
i=1

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])

idx <- which.min(abs(pp_reanalysis$xyCoords$x - station.obs$xyCoords$x))
lon <- pp_reanalysis$xyCoords$x[idx]
  
idx2 <- which.min(abs(pp_reanalysis$xyCoords$y - station.obs$xyCoords$y))
lat <- pp_reanalysis$xyCoords$y[idx2]
  
station.era5 <- subsetGrid(pp_reanalysis, lonLim = lon, latLim = lat)

```



```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)
index.obs <- c(index.obs, index.obs.rv20max)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)
index.trmm <- c(index.trmm, index.trmm.rv20max)

index.era5 <- valueIndex1D(station.era5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.era5.rv20max <- MaxReturnValue(station.era5)
index.era5 <- c(index.era5, index.era5.rv20max)

```
```{r}
cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "pqm")

cal.station <- subsetDimension(cal.station, dimension = "time", indices = which(!is.na(cal.station$Data)))

cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))

index.cal.station <- c(index.cal.station, valueIndex1D(cal.station$Data[!is.na(cal.station$Data)], index.codes = "P98WetAmount"))

index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.pqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "eqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.eqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm <- index.cal.station



cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm", theta = .7)


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm2 <- index.cal.station


```
```{r}
measures <- list()
for (i in c(1:9)) {
  measures[[length(measures)+1]] <- c(abs(index.trmm[i]-index.obs[i]),abs(index.era5[i]-index.obs[i]),abs(index.cal.station.pqm[i]-index.obs[i]), abs(index.cal.station.eqm[i]-index.obs[i]), abs(index.cal.station.gpqm[i]-index.obs[i]), abs(index.cal.station.gpqm2[i] - index.obs[i])) 
}

```

```{r}
normalization <- function(measure){
  measure.norm <- c()
  #measure must be a vector with the value of a certain measure of different calibrations
  for (i in c(1:length(measure))) {
    measure.norm <- c(measure.norm, 1-((measure[i]-min(measure))/(max(measure)-min(measure))))
  }
  return(measure.norm)
}
```

```{r}
norm.vector <- list()
for (i in c(1:length(measures))) {
  norm.vector[[length(norm.vector)+1]] <- normalization(measures[[i]]) 
}
```

```{r}
score.trmm <- c()
for (i in c(1:9)) {
  score.trmm <- c(score.trmm, norm.vector[[i]][1]) 
}
score.trmm <- mean(score.trmm)

score.era5 <- c()
for (i in c(1:9)) {
  score.era5 <- c(score.era5, norm.vector[[i]][2]) 
}
score.era5 <- mean(score.era5)

score.pqm <- c()
for (i in c(1:9)) {
  score.pqm <- c(score.pqm, norm.vector[[i]][3]) 
}
score.pqm <- mean(score.pqm)

score.eqm <- c()
for (i in c(1:9)) {
  score.eqm <- c(score.eqm, norm.vector[[i]][4]) 
}
score.eqm <- mean(score.eqm)

score.gpqm <- c()
for (i in c(1:9)) {
  score.gpqm <- c(score.gpqm, norm.vector[[i]][5]) 
}
score.gpqm <- mean(score.gpqm)

score.gpqm2 <- c()
for (i in c(1:9)) {
  score.gpqm2 <- c(score.gpqm2, norm.vector[[i]][6]) 
}
score.gpqm2 <- mean(score.gpqm2)

scores <- c(score.trmm, score.era5, score.pqm, score.eqm, score.gpqm, score.gpqm2)
names(scores) <- c("TRMM","ERA5","PQM","EQM","GPQM","GPQM2")
scores <- sort(scores, decreasing = T)
scores
```


## Alofi, Niue
```{r}
i=2

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])

idx <- which.min(abs(pp_reanalysis$xyCoords$x - station.obs$xyCoords$x))
lon <- pp_reanalysis$xyCoords$x[idx]
  
idx2 <- which.min(abs(pp_reanalysis$xyCoords$y - station.obs$xyCoords$y))
lat <- pp_reanalysis$xyCoords$y[idx2]
  
station.era5 <- subsetGrid(pp_reanalysis, lonLim = lon, latLim = lat)

```



```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)
index.obs <- c(index.obs, index.obs.rv20max)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)
index.trmm <- c(index.trmm, index.trmm.rv20max)

index.era5 <- valueIndex1D(station.era5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.era5.rv20max <- MaxReturnValue(station.era5)
index.era5 <- c(index.era5, index.era5.rv20max)

```
```{r}
cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "pqm")

cal.station <- subsetDimension(cal.station, dimension = "time", indices = which(!is.na(cal.station$Data)))

cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))

index.cal.station <- c(index.cal.station, valueIndex1D(cal.station$Data[!is.na(cal.station$Data)], index.codes = "P98WetAmount"))

index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.pqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "eqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.eqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm <- index.cal.station



cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm", theta = .7)


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm2 <- index.cal.station


```
```{r}
measures <- list()
for (i in c(1:9)) {
  measures[[length(measures)+1]] <- c(abs(index.trmm[i]-index.obs[i]),abs(index.era5[i]-index.obs[i]),abs(index.cal.station.pqm[i]-index.obs[i]), abs(index.cal.station.eqm[i]-index.obs[i]), abs(index.cal.station.gpqm[i]-index.obs[i]), abs(index.cal.station.gpqm2[i] - index.obs[i])) 
}

```

```{r}
normalization <- function(measure){
  measure.norm <- c()
  #measure must be a vector with the value of a certain measure of different calibrations
  for (i in c(1:length(measure))) {
    measure.norm <- c(measure.norm, 1-((measure[i]-min(measure))/(max(measure)-min(measure))))
  }
  return(measure.norm)
}
```

```{r}
norm.vector <- list()
for (i in c(1:length(measures))) {
  norm.vector[[length(norm.vector)+1]] <- normalization(measures[[i]]) 
}
```

```{r}
score.trmm <- c()
for (i in c(1:9)) {
  score.trmm <- c(score.trmm, norm.vector[[i]][1]) 
}
score.trmm <- mean(score.trmm)

score.era5 <- c()
for (i in c(1:9)) {
  score.era5 <- c(score.era5, norm.vector[[i]][2]) 
}
score.era5 <- mean(score.era5)

score.pqm <- c()
for (i in c(1:9)) {
  score.pqm <- c(score.pqm, norm.vector[[i]][3]) 
}
score.pqm <- mean(score.pqm)

score.eqm <- c()
for (i in c(1:9)) {
  score.eqm <- c(score.eqm, norm.vector[[i]][4]) 
}
score.eqm <- mean(score.eqm)

score.gpqm <- c()
for (i in c(1:9)) {
  score.gpqm <- c(score.gpqm, norm.vector[[i]][5]) 
}
score.gpqm <- mean(score.gpqm)

score.gpqm2 <- c()
for (i in c(1:9)) {
  score.gpqm2 <- c(score.gpqm2, norm.vector[[i]][6]) 
}
score.gpqm2 <- mean(score.gpqm2)

scores <- c(score.trmm, score.era5, score.pqm, score.eqm, score.gpqm, score.gpqm2)
names(scores) <- c("TRMM","ERA5","PQM","EQM","GPQM","GPQM2")
scores <- sort(scores, decreasing = T)
scores
```




## RarotongaIA, Cook Island
```{r}
i=3

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])

idx <- which.min(abs(pp_reanalysis$xyCoords$x - station.obs$xyCoords$x))
lon <- pp_reanalysis$xyCoords$x[idx]
  
idx2 <- which.min(abs(pp_reanalysis$xyCoords$y - station.obs$xyCoords$y))
lat <- pp_reanalysis$xyCoords$y[idx2]
  
station.era5 <- subsetGrid(pp_reanalysis, lonLim = lon, latLim = lat)

```



```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)
index.obs <- c(index.obs, index.obs.rv20max)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)
index.trmm <- c(index.trmm, index.trmm.rv20max)

index.era5 <- valueIndex1D(station.era5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.era5.rv20max <- MaxReturnValue(station.era5)
index.era5 <- c(index.era5, index.era5.rv20max)

```
```{r}
cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "pqm")

cal.station <- subsetDimension(cal.station, dimension = "time", indices = which(!is.na(cal.station$Data)))

cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))

index.cal.station <- c(index.cal.station, valueIndex1D(cal.station$Data[!is.na(cal.station$Data)], index.codes = "P98WetAmount"))

index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.pqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "eqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.eqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm <- index.cal.station



cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm", theta = .7)


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm2 <- index.cal.station


```
```{r}
measures <- list()
for (i in c(1:9)) {
  measures[[length(measures)+1]] <- c(abs(index.trmm[i]-index.obs[i]),abs(index.era5[i]-index.obs[i]),abs(index.cal.station.pqm[i]-index.obs[i]), abs(index.cal.station.eqm[i]-index.obs[i]), abs(index.cal.station.gpqm[i]-index.obs[i]), abs(index.cal.station.gpqm2[i] - index.obs[i])) 
}

```

```{r}
normalization <- function(measure){
  measure.norm <- c()
  #measure must be a vector with the value of a certain measure of different calibrations
  for (i in c(1:length(measure))) {
    measure.norm <- c(measure.norm, 1-((measure[i]-min(measure))/(max(measure)-min(measure))))
  }
  return(measure.norm)
}
```

```{r}
norm.vector <- list()
for (i in c(1:length(measures))) {
  norm.vector[[length(norm.vector)+1]] <- normalization(measures[[i]]) 
}
```

```{r}
score.trmm <- c()
for (i in c(1:9)) {
  score.trmm <- c(score.trmm, norm.vector[[i]][1]) 
}
score.trmm <- mean(score.trmm)

score.era5 <- c()
for (i in c(1:9)) {
  score.era5 <- c(score.era5, norm.vector[[i]][2]) 
}
score.era5 <- mean(score.era5)

score.pqm <- c()
for (i in c(1:9)) {
  score.pqm <- c(score.pqm, norm.vector[[i]][3]) 
}
score.pqm <- mean(score.pqm)

score.eqm <- c()
for (i in c(1:9)) {
  score.eqm <- c(score.eqm, norm.vector[[i]][4]) 
}
score.eqm <- mean(score.eqm)

score.gpqm <- c()
for (i in c(1:9)) {
  score.gpqm <- c(score.gpqm, norm.vector[[i]][5]) 
}
score.gpqm <- mean(score.gpqm)

score.gpqm2 <- c()
for (i in c(1:9)) {
  score.gpqm2 <- c(score.gpqm2, norm.vector[[i]][6]) 
}
score.gpqm2 <- mean(score.gpqm2)

scores <- c(score.trmm, score.era5, score.pqm, score.eqm, score.gpqm, score.gpqm2)
names(scores) <- c("TRMM","ERA5","PQM","EQM","GPQM","GPQM2")
scores <- sort(scores, decreasing = T)
scores
```


## Bells Beach, New Zealand
```{r}
i=4

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])

idx <- which.min(abs(pp_reanalysis$xyCoords$x - station.obs$xyCoords$x))
lon <- pp_reanalysis$xyCoords$x[idx]
  
idx2 <- which.min(abs(pp_reanalysis$xyCoords$y - station.obs$xyCoords$y))
lat <- pp_reanalysis$xyCoords$y[idx2]
  
station.era5 <- subsetGrid(pp_reanalysis, lonLim = lon, latLim = lat)

```



```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)
index.obs <- c(index.obs, index.obs.rv20max)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)
index.trmm <- c(index.trmm, index.trmm.rv20max)

index.era5 <- valueIndex1D(station.era5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.era5.rv20max <- MaxReturnValue(station.era5)
index.era5 <- c(index.era5, index.era5.rv20max)

```
```{r}
cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "pqm")

cal.station <- subsetDimension(cal.station, dimension = "time", indices = which(!is.na(cal.station$Data)))

cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))

index.cal.station <- c(index.cal.station, valueIndex1D(cal.station$Data[!is.na(cal.station$Data)], index.codes = "P98WetAmount"))

index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.pqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "eqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.eqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm <- index.cal.station



cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm", theta = .7)


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm2 <- index.cal.station


```
```{r}
measures <- list()
for (i in c(1:9)) {
  measures[[length(measures)+1]] <- c(abs(index.trmm[i]-index.obs[i]),abs(index.era5[i]-index.obs[i]),abs(index.cal.station.pqm[i]-index.obs[i]), abs(index.cal.station.eqm[i]-index.obs[i]), abs(index.cal.station.gpqm[i]-index.obs[i]), abs(index.cal.station.gpqm2[i] - index.obs[i])) 
}

```

```{r}
normalization <- function(measure){
  measure.norm <- c()
  #measure must be a vector with the value of a certain measure of different calibrations
  for (i in c(1:length(measure))) {
    measure.norm <- c(measure.norm, 1-((measure[i]-min(measure))/(max(measure)-min(measure))))
  }
  return(measure.norm)
}
```

```{r}
norm.vector <- list()
for (i in c(1:length(measures))) {
  norm.vector[[length(norm.vector)+1]] <- normalization(measures[[i]]) 
}
```

```{r}
score.trmm <- c()
for (i in c(1:9)) {
  score.trmm <- c(score.trmm, norm.vector[[i]][1]) 
}
score.trmm <- mean(score.trmm)

score.era5 <- c()
for (i in c(1:9)) {
  score.era5 <- c(score.era5, norm.vector[[i]][2]) 
}
score.era5 <- mean(score.era5)

score.pqm <- c()
for (i in c(1:9)) {
  score.pqm <- c(score.pqm, norm.vector[[i]][3]) 
}
score.pqm <- mean(score.pqm)

score.eqm <- c()
for (i in c(1:9)) {
  score.eqm <- c(score.eqm, norm.vector[[i]][4]) 
}
score.eqm <- mean(score.eqm)

score.gpqm <- c()
for (i in c(1:9)) {
  score.gpqm <- c(score.gpqm, norm.vector[[i]][5]) 
}
score.gpqm <- mean(score.gpqm)

score.gpqm2 <- c()
for (i in c(1:9)) {
  score.gpqm2 <- c(score.gpqm2, norm.vector[[i]][6]) 
}
score.gpqm2 <- mean(score.gpqm2)

scores <- c(score.trmm, score.era5, score.pqm, score.eqm, score.gpqm, score.gpqm2)
names(scores) <- c("TRMM","ERA5","PQM","EQM","GPQM","GPQM2")
scores <- sort(scores, decreasing = T)
scores
```


## ocean buoy?
```{r}
i=5

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])

idx <- which.min(abs(pp_reanalysis$xyCoords$x - station.obs$xyCoords$x))
lon <- pp_reanalysis$xyCoords$x[idx]
  
idx2 <- which.min(abs(pp_reanalysis$xyCoords$y - station.obs$xyCoords$y))
lat <- pp_reanalysis$xyCoords$y[idx2]
  
station.era5 <- subsetGrid(pp_reanalysis, lonLim = lon, latLim = lat)

```



```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)
index.obs <- c(index.obs, index.obs.rv20max)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)
index.trmm <- c(index.trmm, index.trmm.rv20max)

index.era5 <- valueIndex1D(station.era5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.era5.rv20max <- MaxReturnValue(station.era5)
index.era5 <- c(index.era5, index.era5.rv20max)

```
```{r}
cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "pqm")

cal.station <- subsetDimension(cal.station, dimension = "time", indices = which(!is.na(cal.station$Data)))

cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))

index.cal.station <- c(index.cal.station, valueIndex1D(cal.station$Data[!is.na(cal.station$Data)], index.codes = "P98WetAmount"))

index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.pqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "eqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.eqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm <- index.cal.station



cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm", theta = .7)


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm2 <- index.cal.station


```
```{r}
measures <- list()
for (i in c(1:9)) {
  measures[[length(measures)+1]] <- c(abs(index.trmm[i]-index.obs[i]),abs(index.era5[i]-index.obs[i]),abs(index.cal.station.pqm[i]-index.obs[i]), abs(index.cal.station.eqm[i]-index.obs[i]), abs(index.cal.station.gpqm[i]-index.obs[i]), abs(index.cal.station.gpqm2[i] - index.obs[i])) 
}

```

```{r}
normalization <- function(measure){
  measure.norm <- c()
  #measure must be a vector with the value of a certain measure of different calibrations
  for (i in c(1:length(measure))) {
    measure.norm <- c(measure.norm, 1-((measure[i]-min(measure))/(max(measure)-min(measure))))
  }
  return(measure.norm)
}
```

```{r}
norm.vector <- list()
for (i in c(1:length(measures))) {
  norm.vector[[length(norm.vector)+1]] <- normalization(measures[[i]]) 
}
```

```{r}
score.trmm <- c()
for (i in c(1:9)) {
  score.trmm <- c(score.trmm, norm.vector[[i]][1]) 
}
score.trmm <- mean(score.trmm)

score.era5 <- c()
for (i in c(1:9)) {
  score.era5 <- c(score.era5, norm.vector[[i]][2]) 
}
score.era5 <- mean(score.era5)

score.pqm <- c()
for (i in c(1:9)) {
  score.pqm <- c(score.pqm, norm.vector[[i]][3]) 
}
score.pqm <- mean(score.pqm)

score.eqm <- c()
for (i in c(1:9)) {
  score.eqm <- c(score.eqm, norm.vector[[i]][4]) 
}
score.eqm <- mean(score.eqm)

score.gpqm <- c()
for (i in c(1:9)) {
  score.gpqm <- c(score.gpqm, norm.vector[[i]][5]) 
}
score.gpqm <- mean(score.gpqm)

score.gpqm2 <- c()
for (i in c(1:9)) {
  score.gpqm2 <- c(score.gpqm2, norm.vector[[i]][6]) 
}
score.gpqm2 <- mean(score.gpqm2)

scores <- c(score.trmm, score.era5, score.pqm, score.eqm, score.gpqm, score.gpqm2)
names(scores) <- c("TRMM","ERA5","PQM","EQM","GPQM","GPQM2")
scores <- sort(scores, decreasing = T)
scores
```


## Aoloau, American Samoa
```{r}
i=6

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])

idx <- which.min(abs(pp_reanalysis$xyCoords$x - station.obs$xyCoords$x))
lon <- pp_reanalysis$xyCoords$x[idx]
  
idx2 <- which.min(abs(pp_reanalysis$xyCoords$y - station.obs$xyCoords$y))
lat <- pp_reanalysis$xyCoords$y[idx2]
  
station.era5 <- subsetGrid(pp_reanalysis, lonLim = lon, latLim = lat)

```



```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)
index.obs <- c(index.obs, index.obs.rv20max)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)
index.trmm <- c(index.trmm, index.trmm.rv20max)

index.era5 <- valueIndex1D(station.era5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.era5.rv20max <- MaxReturnValue(station.era5)
index.era5 <- c(index.era5, index.era5.rv20max)

```
```{r}
cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "pqm")

cal.station <- subsetDimension(cal.station, dimension = "time", indices = which(!is.na(cal.station$Data)))

cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))

index.cal.station <- c(index.cal.station, valueIndex1D(cal.station$Data[!is.na(cal.station$Data)], index.codes = "P98WetAmount"))

index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.pqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "eqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.eqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm <- index.cal.station



cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm", theta = .7)


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm2 <- index.cal.station


```
```{r}
measures <- list()
for (i in c(1:9)) {
  measures[[length(measures)+1]] <- c(abs(index.trmm[i]-index.obs[i]),abs(index.era5[i]-index.obs[i]),abs(index.cal.station.pqm[i]-index.obs[i]), abs(index.cal.station.eqm[i]-index.obs[i]), abs(index.cal.station.gpqm[i]-index.obs[i]), abs(index.cal.station.gpqm2[i] - index.obs[i])) 
}

```

```{r}
normalization <- function(measure){
  measure.norm <- c()
  #measure must be a vector with the value of a certain measure of different calibrations
  for (i in c(1:length(measure))) {
    measure.norm <- c(measure.norm, 1-((measure[i]-min(measure))/(max(measure)-min(measure))))
  }
  return(measure.norm)
}
```

```{r}
norm.vector <- list()
for (i in c(1:length(measures))) {
  norm.vector[[length(norm.vector)+1]] <- normalization(measures[[i]]) 
}
```

```{r}
score.trmm <- c()
for (i in c(1:9)) {
  score.trmm <- c(score.trmm, norm.vector[[i]][1]) 
}
score.trmm <- mean(score.trmm)

score.era5 <- c()
for (i in c(1:9)) {
  score.era5 <- c(score.era5, norm.vector[[i]][2]) 
}
score.era5 <- mean(score.era5)

score.pqm <- c()
for (i in c(1:9)) {
  score.pqm <- c(score.pqm, norm.vector[[i]][3]) 
}
score.pqm <- mean(score.pqm)

score.eqm <- c()
for (i in c(1:9)) {
  score.eqm <- c(score.eqm, norm.vector[[i]][4]) 
}
score.eqm <- mean(score.eqm)

score.gpqm <- c()
for (i in c(1:9)) {
  score.gpqm <- c(score.gpqm, norm.vector[[i]][5]) 
}
score.gpqm <- mean(score.gpqm)

score.gpqm2 <- c()
for (i in c(1:9)) {
  score.gpqm2 <- c(score.gpqm2, norm.vector[[i]][6]) 
}
score.gpqm2 <- mean(score.gpqm2)

scores <- c(score.trmm, score.era5, score.pqm, score.eqm, score.gpqm, score.gpqm2)
names(scores) <- c("TRMM","ERA5","PQM","EQM","GPQM","GPQM2")
scores <- sort(scores, decreasing = T)
scores
```

## Nu'uuli, American Samoa
```{r}
i=7

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])

idx <- which.min(abs(pp_reanalysis$xyCoords$x - station.obs$xyCoords$x))
lon <- pp_reanalysis$xyCoords$x[idx]
  
idx2 <- which.min(abs(pp_reanalysis$xyCoords$y - station.obs$xyCoords$y))
lat <- pp_reanalysis$xyCoords$y[idx2]
  
station.era5 <- subsetGrid(pp_reanalysis, lonLim = lon, latLim = lat)

```



```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)
index.obs <- c(index.obs, index.obs.rv20max)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)
index.trmm <- c(index.trmm, index.trmm.rv20max)

index.era5 <- valueIndex1D(station.era5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.era5.rv20max <- MaxReturnValue(station.era5)
index.era5 <- c(index.era5, index.era5.rv20max)

```
```{r}
cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "pqm")

cal.station <- subsetDimension(cal.station, dimension = "time", indices = which(!is.na(cal.station$Data)))

cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))

index.cal.station <- c(index.cal.station, valueIndex1D(cal.station$Data[!is.na(cal.station$Data)], index.codes = "P98WetAmount"))

index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.pqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "eqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.eqm <- index.cal.station


cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm")


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm <- index.cal.station



cal.station <- biasCorrection(y = station.obs, x = station.trmm, precipitation = TRUE,  method = "gpqm", theta = .7)


cal.station$Dates$start <- as.POSIXct(cal.station$Dates$start,tz = "GMT")
cal.station$Dates$end <- as.POSIXct(cal.station$Dates$end,tz = "GMT")

index.cal.station <- valueIndex1D(cal.station$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.rv20max <- MaxReturnValue(cal.station)

index.cal.station <- c(index.cal.station, index.cal.station.rv20max)

index.cal.station.gpqm2 <- index.cal.station


```
```{r}
measures <- list()
for (i in c(1:9)) {
  measures[[length(measures)+1]] <- c(abs(index.trmm[i]-index.obs[i]),abs(index.era5[i]-index.obs[i]),abs(index.cal.station.pqm[i]-index.obs[i]), abs(index.cal.station.eqm[i]-index.obs[i]), abs(index.cal.station.gpqm[i]-index.obs[i]), abs(index.cal.station.gpqm2[i] - index.obs[i])) 
}

```

```{r}
normalization <- function(measure){
  measure.norm <- c()
  #measure must be a vector with the value of a certain measure of different calibrations
  for (i in c(1:length(measure))) {
    measure.norm <- c(measure.norm, 1-((measure[i]-min(measure))/(max(measure)-min(measure))))
  }
  return(measure.norm)
}
```

```{r}
norm.vector <- list()
for (i in c(1:length(measures))) {
  norm.vector[[length(norm.vector)+1]] <- normalization(measures[[i]]) 
}
```

```{r}
score.trmm <- c()
for (i in c(1:9)) {
  score.trmm <- c(score.trmm, norm.vector[[i]][1]) 
}
score.trmm <- mean(score.trmm)

score.era5 <- c()
for (i in c(1:9)) {
  score.era5 <- c(score.era5, norm.vector[[i]][2]) 
}
score.era5 <- mean(score.era5)

score.pqm <- c()
for (i in c(1:9)) {
  score.pqm <- c(score.pqm, norm.vector[[i]][3]) 
}
score.pqm <- mean(score.pqm)

score.eqm <- c()
for (i in c(1:9)) {
  score.eqm <- c(score.eqm, norm.vector[[i]][4]) 
}
score.eqm <- mean(score.eqm)

score.gpqm <- c()
for (i in c(1:9)) {
  score.gpqm <- c(score.gpqm, norm.vector[[i]][5]) 
}
score.gpqm <- mean(score.gpqm)

score.gpqm2 <- c()
for (i in c(1:9)) {
  score.gpqm2 <- c(score.gpqm2, norm.vector[[i]][6]) 
}
score.gpqm2 <- mean(score.gpqm2)

scores <- c(score.trmm, score.era5, score.pqm, score.eqm, score.gpqm, score.gpqm2)
names(scores) <- c("TRMM","ERA5","PQM","EQM","GPQM","GPQM2")
scores <- sort(scores, decreasing = T)
scores
```



