---
title: "SCPZ displacement"
output: 
  html_notebook:
    theme: united
    toc: yes
    toc_depth: 5
---



```{r}
library(loadeR)
library(transformeR)
library(visualizeR)
library(clue)
library(scales)
library(lubridate)
```
# Period 1998-2020
```{r}
load("C:/Users/usuario/Desktop/TRMM-Calibration/Data/slp.RData")
load("C:/Users/usuario/Desktop/TRMM-Calibration/Data/kmModel5.RData")
load("C:/Users/usuario/Desktop/TRMM-Calibration/Data/pp_reanalysis.RData")
```

```{r}
computeSPI <- function(slp, time.scale = "daily", season = "complete", export.csv = FALSE){
  if (time.scale %in% c("daily", "monthly", "annual")){
    if(season %in% c("complete", "wet")){
      if(season == "wet"){
        
        s <- c(11,12,1,2,3,4)
        slp <- subsetGrid(slp, season = s)
        
      }
      if(time.scale == "daily"){
        
        apia.slp <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(-171.7666636)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-13.83333)))])
        
        suva.slp <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(178.44149)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-18.1416)))])
        
        spi <- scale(suva.slp$Data - apia.slp$Data)
        
        df <- data.frame(apia.slp$Dates$start, spi)
        name <- "daily_spi.csv"
        
      }else if(time.scale == "monthly"){
        
        slp <- aggregateGrid(slp , aggr.m = list(FUN ="mean"))
        
        apia.slp <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(-171.7666636)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-13.83333)))])
        
        suva.slp <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(178.44149)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-18.1416)))])
        
        spi <- scale(suva.slp$Data - apia.slp$Data)
        
        df <- data.frame(apia.slp$Dates$start, spi)
        
        name <- "monthly_spi.csv"
        
      }else{
        
        slp <- aggregateGrid(slp , aggr.m = list(FUN ="mean"), aggr.y = list(FUN = "mean"))
        
        apia.slp <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(-171.7666636)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-13.83333)))])
        
        suva.slp <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(178.44149)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-18.1416)))])
        
        spi <- scale(suva.slp$Data - apia.slp$Data)
        
        df <- data.frame(apia.slp$Dates$start, spi)
        name <- "annual_spi.csv"
        
      }
      
      if(export.csv == TRUE){
        write.csv(df, name)
      }
      
      return(df)
    }else{
      stop("Season selected is not correct.")
    }
    
  }else{
      stop("The time scale is not valid!")
  }
  
  
}

```

# Cluster 1

```{r}
cl1.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 1)

cl1.slp.apia <- subsetGrid(cl1.slp, lonLim = cl1.slp$xyCoords$x[which.min(abs(cl1.slp$xyCoords$x-(-171.7666636)))], latLim = cl1.slp$xyCoords$y[which.min(abs(cl1.slp$xyCoords$y-(-13.83333)))])
cl1.slp.suva <- subsetGrid(cl1.slp, lonLim = cl1.slp$xyCoords$x[which.min(abs(cl1.slp$xyCoords$x-(178.44149)))], latLim = cl1.slp$xyCoords$y[which.min(abs(cl1.slp$xyCoords$y-(-18.1416)))])
cl1.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 1)

cl1.spi <- scale(cl1.slp.suva$Data - cl1.slp.apia$Data)

```

```{r}
spatialPlot(climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi > 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at positive phase")
```


```{r}
spatialPlot(climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi < 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at negative phase")
```

# Cluster 2

```{r}
cl2.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 2)

cl2.slp.apia <- subsetGrid(cl2.slp, lonLim = cl2.slp$xyCoords$x[which.min(abs(cl2.slp$xyCoords$x-(-171.7666636)))], latLim = cl2.slp$xyCoords$y[which.min(abs(cl2.slp$xyCoords$y-(-13.83333)))])
cl2.slp.suva <- subsetGrid(cl2.slp, lonLim = cl2.slp$xyCoords$x[which.min(abs(cl2.slp$xyCoords$x-(178.44149)))], latLim = cl2.slp$xyCoords$y[which.min(abs(cl2.slp$xyCoords$y-(-18.1416)))])
cl2.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 2)

cl2.spi <- scale(cl2.slp.suva$Data - cl2.slp.apia$Data)

```

```{r}
spatialPlot(climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi > 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at positive phase")
```


```{r}
spatialPlot(climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi < 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at negative phase")
```

# Cluster 3

```{r}
cl3.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 3)

cl3.slp.apia <- subsetGrid(cl3.slp, lonLim = cl3.slp$xyCoords$x[which.min(abs(cl3.slp$xyCoords$x-(-171.7666636)))], latLim = cl3.slp$xyCoords$y[which.min(abs(cl3.slp$xyCoords$y-(-13.83333)))])
cl3.slp.suva <- subsetGrid(cl3.slp, lonLim = cl3.slp$xyCoords$x[which.min(abs(cl3.slp$xyCoords$x-(178.44149)))], latLim = cl3.slp$xyCoords$y[which.min(abs(cl3.slp$xyCoords$y-(-18.1416)))])
cl3.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 3)

cl3.spi <- scale(cl3.slp.suva$Data - cl3.slp.apia$Data)

```

```{r}
spatialPlot(climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi > 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at positive phase")
```


```{r}
spatialPlot(climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi < 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at negative phase")
```

# Cluster 4

```{r}
cl4.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 4)

cl4.slp.apia <- subsetGrid(cl4.slp, lonLim = cl4.slp$xyCoords$x[which.min(abs(cl4.slp$xyCoords$x-(-171.7666636)))], latLim = cl4.slp$xyCoords$y[which.min(abs(cl4.slp$xyCoords$y-(-13.83333)))])
cl4.slp.suva <- subsetGrid(cl4.slp, lonLim = cl4.slp$xyCoords$x[which.min(abs(cl4.slp$xyCoords$x-(178.44149)))], latLim = cl4.slp$xyCoords$y[which.min(abs(cl4.slp$xyCoords$y-(-18.1416)))])
cl4.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 4)

cl4.spi <- scale(cl4.slp.suva$Data - cl4.slp.apia$Data)

```

```{r}
spatialPlot(climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi > 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at positive phase")
```


```{r}
spatialPlot(climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi < 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at negative phase")
```

# Cluster 5

```{r}
cl5.slp <- subsetDimension(slp, dimension = "time", indices = kmModel5$cluster == 5)

cl5.slp.apia <- subsetGrid(cl5.slp, lonLim = cl5.slp$xyCoords$x[which.min(abs(cl5.slp$xyCoords$x-(-171.7666636)))], latLim = cl5.slp$xyCoords$y[which.min(abs(cl5.slp$xyCoords$y-(-13.83333)))])
cl5.slp.suva <- subsetGrid(cl5.slp, lonLim = cl5.slp$xyCoords$x[which.min(abs(cl5.slp$xyCoords$x-(178.44149)))], latLim = cl5.slp$xyCoords$y[which.min(abs(cl5.slp$xyCoords$y-(-18.1416)))])
cl5.pp <- subsetDimension(pp_reanalysis, dimension = "time", indices = kmModel5$cluster == 5)

cl5.spi <- scale(cl5.slp.suva$Data - cl5.slp.apia$Data)

```

```{r}
spatialPlot(climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi > 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at positive phase")
```


```{r}
spatialPlot(climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi < 0))),
            rev.colors = T, backdrop.theme = 'countries', main = "SPCZ at negative phase")
```
```{r}
cl1.diff <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi < 0)))
cl1.diff$Data <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi < 0)))$Data - climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi > 0)))$Data

spatialPlot(cl1.diff,rev.colors = T, backdrop.theme = 'countries', center = 0,main = "SPI Phase Diff SPCZ Cl1", center = 0, color.theme = 'RdBu')
```

```{r}
cl2.diff <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi < 0)))
cl2.diff$Data <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi < 0)))$Data - climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi > 0)))$Data

spatialPlot(cl2.diff,rev.colors = T, backdrop.theme = 'countries', center = 0,main = "SPI Phase Diff SPCZ Cl2", center = 0, color.theme = 'RdBu')
```

```{r}
cl3.diff <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi < 0)))
cl3.diff$Data <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi < 0)))$Data - climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi > 0)))$Data

spatialPlot(cl3.diff,rev.colors = T, backdrop.theme = 'countries', center = 0,main = "SPI Phase Diff SPCZ Cl3", color.theme = 'RdBu')
```

```{r}
cl4.diff <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi < 0)))
cl4.diff$Data <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi < 0)))$Data - climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi > 0)))$Data

spatialPlot(cl4.diff,rev.colors = T, backdrop.theme = 'countries', main = "SPI Phase Diff SPCZ Cl4", center = 0,color.theme = 'RdBu')
```

```{r}
cl5.diff <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi < 0)))
cl5.diff$Data <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi < 0)))$Data - climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi > 0)))$Data

spatialPlot(cl5.diff,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "SPI Phase Diff SPCZ Cl5",color.theme = 'RdBu')
```

```{r}
mg <- makeMultiGrid(cl1.diff,cl2.diff,cl3.diff,cl4.diff,cl5.diff, skip.temporal.check = T)
```

```{r}
spatialPlot(mg, rev.colors = T , backdrop.theme = 'countries', names.attr = c("WT1","WT2","WT3","WT4","WT5"), center = 0, color.theme = 'RdBu')
```
```{r}
cl1.diff.neg <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi < 0)))
cl1.diff.neg$Data <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi < 0)))$Data - climatology(cl1.pp)$Data

spatialPlot(cl1.diff.neg,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI- phase Cl1",color.theme = 'RdBu')
```

```{r}
cl2.diff.neg <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi < 0)))
cl2.diff.neg$Data <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi < 0)))$Data - climatology(cl2.pp)$Data

spatialPlot(cl2.diff.neg,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI- phase Cl2",color.theme = 'RdBu')
```

```{r}
cl3.diff.neg <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi < 0)))
cl3.diff.neg$Data <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi < 0)))$Data - climatology(cl3.pp)$Data

spatialPlot(cl3.diff.neg,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI- phase Cl3",color.theme = 'RdBu')
```

```{r}
cl4.diff.neg <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi < 0)))
cl4.diff.neg$Data <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi < 0)))$Data - climatology(cl4.pp)$Data

spatialPlot(cl4.diff.neg,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI- phase Cl4",color.theme = 'RdBu')
```


```{r}
cl5.diff.neg <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi < 0)))
cl5.diff.neg$Data <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi < 0)))$Data - climatology(cl5.pp)$Data

spatialPlot(cl5.diff.neg,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI- phase Cl5",color.theme = 'RdBu')
```

```{r}
mg <- makeMultiGrid(cl1.diff.neg,cl2.diff.neg,cl3.diff.neg,cl4.diff.neg,cl5.diff.neg, skip.temporal.check = T)
```

```{r}
spatialPlot(mg, rev.colors = T , backdrop.theme = 'countries', names.attr = c("WT1","WT2","WT3","WT4","WT5"), center = 0, color.theme = 'RdBu', at = seq(-6.5,6.5,.5))
```
```{r}
cl1.diff.pos <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi > 0)))
cl1.diff.pos$Data <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi > 0)))$Data - climatology(cl1.pp)$Data

spatialPlot(cl1.diff.pos,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI+ phase Cl1",color.theme = 'RdBu')
```

```{r}
cl2.diff.pos <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi > 0)))
cl2.diff.pos$Data <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi > 0)))$Data - climatology(cl2.pp)$Data

spatialPlot(cl2.diff.pos,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI+ phase Cl2",color.theme = 'RdBu')
```

```{r}
cl3.diff.pos <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi > 0)))
cl3.diff.pos$Data <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi > 0)))$Data - climatology(cl3.pp)$Data

spatialPlot(cl3.diff.pos,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI+ phase Cl3",color.theme = 'RdBu')
```

```{r}
cl4.diff.pos <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi > 0)))
cl4.diff.pos$Data <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi > 0)))$Data - climatology(cl4.pp)$Data

spatialPlot(cl4.diff.pos,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI+ phase Cl4",color.theme = 'RdBu')
```


```{r}
cl5.diff.pos <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi > 0)))
cl5.diff.pos$Data <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi > 0)))$Data - climatology(cl5.pp)$Data

spatialPlot(cl5.diff.pos,rev.colors = T, backdrop.theme = 'countries', center = 0, main = "Anomalies SPI+ phase Cl5",color.theme = 'RdBu')
```

```{r}
mg <- makeMultiGrid(cl1.diff.pos,cl2.diff.pos,cl3.diff.pos,cl4.diff.pos,cl5.diff.pos, skip.temporal.check = T)
```

```{r}
spatialPlot(mg, rev.colors = T , backdrop.theme = 'countries', names.attr = c("WT1","WT2","WT3","WT4","WT5"), center = 0, color.theme = 'RdBu', at = seq(-6.5, 6.5, 0.5))
```


```{r}
slp.apia <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(-171.7666636)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-13.83333)))])
slp.suva <- subsetGrid(slp, lonLim = slp$xyCoords$x[which.min(abs(slp$xyCoords$x-(178.44149)))], latLim = slp$xyCoords$y[which.min(abs(slp$xyCoords$y-(-18.1416)))])

spi <- scale(slp.suva$Data - slp.apia$Data)

```

```{r}
terciles <- quantile(spi, probs = c(1/3, 2/3))

```


```{r}
cl1.diff.neg <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi < terciles[1])))
cl1.diff.neg$Data <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi < terciles[1])))$Data - climatology(cl1.pp)$Data
cl1.diff.pos<- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi > terciles[2])))
cl1.diff.pos$Data <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which(cl1.spi > terciles[2])))$Data - climatology(cl1.pp)$Data
cl1.diff.neutral<- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which((cl1.spi < terciles[2]) & (cl1.spi > terciles[1]))))
cl1.diff.neutral$Data <- climatology(subsetDimension(cl1.pp, dimension = "time", indices = which((cl1.spi < terciles[2]) & (cl1.spi > terciles[1]))))$Data - climatology(cl1.pp)$Data

cl2.diff.neg <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi < terciles[1])))
cl2.diff.neg$Data <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi < terciles[1])))$Data - climatology(cl2.pp)$Data
cl2.diff.pos<- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi > terciles[2])))
cl2.diff.pos$Data <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which(cl2.spi > terciles[2])))$Data - climatology(cl2.pp)$Data
cl2.diff.neutral<- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which((cl2.spi < terciles[2]) & (cl2.spi > terciles[1]))))
cl2.diff.neutral$Data <- climatology(subsetDimension(cl2.pp, dimension = "time", indices = which((cl2.spi < terciles[2]) & (cl2.spi > terciles[1]))))$Data - climatology(cl2.pp)$Data

cl3.diff.neg <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi < terciles[1])))
cl3.diff.neg$Data <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi < 0)))$Data - climatology(cl3.pp)$Data
cl3.diff.pos<- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi > terciles[2])))
cl3.diff.pos$Data <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which(cl3.spi > terciles[2])))$Data - climatology(cl3.pp)$Data
cl3.diff.neutral<- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which((cl3.spi < terciles[2]) & (cl3.spi > terciles[1]))))
cl3.diff.neutral$Data <- climatology(subsetDimension(cl3.pp, dimension = "time", indices = which((cl3.spi < terciles[2]) & (cl3.spi > terciles[1]))))$Data - climatology(cl3.pp)$Data

cl4.diff.neg <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi < terciles[1])))
cl4.diff.neg$Data <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi < terciles[1])))$Data - climatology(cl4.pp)$Data
cl4.diff.pos<- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi > terciles[2])))
cl4.diff.pos$Data <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which(cl4.spi > terciles[2])))$Data - climatology(cl4.pp)$Data
cl4.diff.neutral<- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which((cl4.spi < terciles[2]) & (cl4.spi > terciles[1]))))
cl4.diff.neutral$Data <- climatology(subsetDimension(cl4.pp, dimension = "time", indices = which((cl4.spi < terciles[2]) & (cl4.spi > terciles[1]))))$Data - climatology(cl4.pp)$Data


cl5.diff.neg <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi < terciles[1])))
cl5.diff.neg$Data <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi < terciles[1])))$Data - climatology(cl5.pp)$Data
cl5.diff.pos<- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi > terciles[2])))
cl5.diff.pos$Data <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which(cl5.spi > terciles[2])))$Data - climatology(cl5.pp)$Data
cl5.diff.neutral<- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which((cl5.spi < terciles[2]) & (cl5.spi > terciles[1]))))
cl5.diff.neutral$Data <- climatology(subsetDimension(cl5.pp, dimension = "time", indices = which((cl5.spi < terciles[2]) & (cl5.spi > terciles[1]))))$Data - climatology(cl5.pp)$Data
```

```{r}
mg.neg <- makeMultiGrid(cl1.diff.neg,cl2.diff.neg,cl3.diff.neg,cl4.diff.neg,cl5.diff.neg, skip.temporal.check = T)

mg.pos <- makeMultiGrid(cl1.diff.pos,cl2.diff.pos,cl3.diff.pos,cl4.diff.pos,cl5.diff.pos, skip.temporal.check = T)

mg.neutral <- makeMultiGrid(cl1.diff.neutral,cl2.diff.neutral,cl3.diff.neutral,cl4.diff.neutral,cl5.diff.neutral, skip.temporal.check = T)
```

```{r}
spatialPlot(mg.neg, rev.colors = T , backdrop.theme = 'countries', names.attr = c("WT1","WT2","WT3","WT4","WT5"), center = 0, color.theme = 'RdBu', at = seq(-8,8,.5))
```
```{r}
spatialPlot(mg.pos, rev.colors = T , backdrop.theme = 'countries', names.attr = c("WT1","WT2","WT3","WT4","WT5"), center = 0, color.theme = 'RdBu', at = seq(-7,7,.5))
```

```{r}
spatialPlot(mg.neutral, rev.colors = T , backdrop.theme = 'countries', names.attr = c("WT1","WT2","WT3","WT4","WT5"), center = 0, color.theme = 'RdBu', at = seq(-3,3,.5))
```

```{r}
big.mg <- makeMultiGrid(cl1.diff.neg,cl1.diff.neutral,cl1.diff.pos,cl2.diff.neg,cl2.diff.neutral,cl2.diff.pos,cl3.diff.neg,cl3.diff.neutral,cl3.diff.pos,cl4.diff.neg,cl4.diff.neutral,cl4.diff.pos,cl5.diff.neg,cl5.diff.neutral,cl5.diff.pos, skip.temporal.check = T)
```


```{r}
spatialPlot(big.mg,rev.colors = T , backdrop.theme = 'countries',color.theme = 'RdBu', at = seq(-8,8,.5), layout = c(3,5),colorkey = list(space ="bottom",height=1, width=1), names.attr = c("WT1 T1","WT1 T2","WT1 T3","WT2 T1","WT2 T2","WT2 T3","WT3 T1","WT3 T2","WT3 T3","WT4 T1","WT4 T2","WT4 T3","WT5 T1","WT5 T2","WT5 T3"), as.table = T)
```


```{r}
cyclones <- read.csv('C:/Users/usuario/Desktop/Master/tfm/Notebooks_TFM/SP_cyclones_time_series_1998_2020.csv')
cyclones$Date <- as.Date(cyclones$Date)
cyclones <- cyclones[,2:3]
```

```{r}
cyclones.cl1 <- cyclones[which(kmModel5$cluster == 1),]
cyclones.cl2 <- cyclones[which(kmModel5$cluster == 2),]
cyclones.cl3 <- cyclones[which(kmModel5$cluster == 3),]
cyclones.cl4 <- cyclones[which(kmModel5$cluster == 4),]
cyclones.cl5 <- cyclones[which(kmModel5$cluster == 5),]
```

```{r}
cyclones.cl1.pos <- cyclones.cl1[which(cl1.spi > terciles[2]),]
cyclones.cl1.med <- cyclones.cl1[which((cl1.spi < terciles[2]) & (cl1.spi > terciles[1])),]
cyclones.cl1.neg <- cyclones.cl1[which(cl1.spi < terciles[1]),]
```

```{r}
barplot(c(sum(cyclones.cl1.neg$cyclones_generation_centers), sum(cyclones.cl1.med$cyclones_generation_centers), sum(cyclones.cl1.pos$cyclones_generation_centers)),
        names.arg = c("WT1-T1", "WT1-T2", "WT1-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")
```

```{r}
cyclones.cl2.pos <- cyclones.cl2[which(cl2.spi > terciles[2]),]
cyclones.cl2.med <- cyclones.cl2[which((cl2.spi < terciles[2]) & (cl2.spi > terciles[1])),]
cyclones.cl2.neg <- cyclones.cl2[which(cl2.spi < terciles[1]),]
```

```{r}
barplot(c(sum(cyclones.cl2.neg$cyclones_generation_centers), sum(cyclones.cl2.med$cyclones_generation_centers), sum(cyclones.cl2.pos$cyclones_generation_centers)),
        names.arg = c("WT2-T1", "WT2-T2", "WT2-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")
```

```{r}
cyclones.cl3.pos <- cyclones.cl3[which(cl3.spi > terciles[2]),]
cyclones.cl3.med <- cyclones.cl3[which((cl3.spi < terciles[2]) & (cl3.spi > terciles[1])),]
cyclones.cl3.neg <- cyclones.cl3[which(cl3.spi < terciles[1]),]
```

```{r}
barplot(c(sum(cyclones.cl3.neg$cyclones_generation_centers), sum(cyclones.cl3.med$cyclones_generation_centers), sum(cyclones.cl3.pos$cyclones_generation_centers)),
        names.arg = c("WT3-T1", "WT3-T2", "WT3-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")
```


```{r}
cyclones.cl4.pos <- cyclones.cl4[which(cl4.spi > terciles[2]),]
cyclones.cl4.med <- cyclones.cl4[which((cl4.spi < terciles[2]) & (cl4.spi > terciles[1])),]
cyclones.cl4.neg <- cyclones.cl4[which(cl4.spi < terciles[1]),]
```

```{r}
barplot(c(sum(cyclones.cl4.neg$cyclones_generation_centers), sum(cyclones.cl4.med$cyclones_generation_centers), sum(cyclones.cl4.pos$cyclones_generation_centers)),
        names.arg = c("WT4-T1", "WT4-T2", "WT4-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")
```


```{r}
cyclones.cl5.pos <- cyclones.cl5[which(cl5.spi > terciles[2]),]
cyclones.cl5.med <- cyclones.cl5[which((cl5.spi < terciles[2]) & (cl5.spi > terciles[1])),]
cyclones.cl5.neg <- cyclones.cl5[which(cl5.spi < terciles[1]),]
```

```{r}
barplot(c(sum(cyclones.cl5.neg$cyclones_generation_centers), sum(cyclones.cl5.med$cyclones_generation_centers), sum(cyclones.cl5.pos$cyclones_generation_centers)),
        names.arg = c("WT5-T1", "WT5-T2", "WT5-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")
```

```{r}
par(mfrow=c(2,3))

barplot(c(sum(cyclones.cl1.neg$cyclones_generation_centers), sum(cyclones.cl1.med$cyclones_generation_centers), sum(cyclones.cl1.pos$cyclones_generation_centers)),
        names.arg = c("WT1-T1", "WT1-T2", "WT1-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")

barplot(c(sum(cyclones.cl2.neg$cyclones_generation_centers), sum(cyclones.cl2.med$cyclones_generation_centers), sum(cyclones.cl2.pos$cyclones_generation_centers)),
        names.arg = c("WT2-T1", "WT2-T2", "WT2-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")

barplot(c(sum(cyclones.cl3.neg$cyclones_generation_centers), sum(cyclones.cl3.med$cyclones_generation_centers), sum(cyclones.cl3.pos$cyclones_generation_centers)),
        names.arg = c("WT3-T1", "WT3-T2", "WT3-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")

barplot(c(sum(cyclones.cl4.neg$cyclones_generation_centers), sum(cyclones.cl4.med$cyclones_generation_centers), sum(cyclones.cl4.pos$cyclones_generation_centers)),
        names.arg = c("WT4-T1", "WT4-T2", "WT4-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")

barplot(c(sum(cyclones.cl5.neg$cyclones_generation_centers), sum(cyclones.cl5.med$cyclones_generation_centers), sum(cyclones.cl5.pos$cyclones_generation_centers)),
        names.arg = c("WT5-T1", "WT5-T2", "WT5-T3"), col = c("red","orange","blue"), ylab = "Nº cyclones generation centers")
```
```{r}
vals <- cbind(c(sum(cyclones.cl1.neg$cyclones_generation_centers), sum(cyclones.cl1.med$cyclones_generation_centers), sum(cyclones.cl1.pos$cyclones_generation_centers)),c(sum(cyclones.cl2.neg$cyclones_generation_centers), sum(cyclones.cl2.med$cyclones_generation_centers), sum(cyclones.cl2.pos$cyclones_generation_centers)),c(sum(cyclones.cl3.neg$cyclones_generation_centers), sum(cyclones.cl3.med$cyclones_generation_centers), sum(cyclones.cl3.pos$cyclones_generation_centers)),c(sum(cyclones.cl4.neg$cyclones_generation_centers), sum(cyclones.cl4.med$cyclones_generation_centers), sum(cyclones.cl4.pos$cyclones_generation_centers)),c(sum(cyclones.cl5.neg$cyclones_generation_centers), sum(cyclones.cl5.med$cyclones_generation_centers), sum(cyclones.cl5.pos$cyclones_generation_centers)))
```

```{r}
barplot(vals, beside = T, col = c("red", "orange","blue"), names.arg = c("WT1","WT2","WT3","WT4","WT5"), 
        horiz = T, xlab = "Number of cyclone generation centers")
legend("topright", 
       legend = c("T1", "T2", "T3"), 
       fill = c("blue", "orange","red"),
       cex = 0.75)
```

```{r}
vals <- rbind(vals, c(sum(vals[,1]), sum(vals[,2]),sum(vals[,3]),sum(vals[,4]),sum(vals[,5])))
```

```{r}
col.barplot <- c(alpha("#006837",.25),alpha("#006837",.5),alpha("#006837",.75),"#006837",
                 alpha("#66C2A5",.25),alpha("#66C2A5",.5),alpha("#66C2A5",.75),"#66C2A5",
                 alpha("#FFFFBF",.25),alpha("#FFFFBF",.5),alpha("#FFFFBF",.75),"#FFFFBF",
                 alpha("#5E4FA2",.25),alpha("#5E4FA2",.5),alpha("#5E4FA2",.75),"#5E4FA2",
                 alpha("#F46D43",.25),alpha("#F46D43",.5),alpha("#F46D43",.75),"#F46D43")
```

```{r}
#rownames(vals) <- c("T3","T2","T1","T1+T2+T3")
barplot(vals, beside = T, col = col.barplot, names.arg = c("WT1","WT2","WT3","WT4","WT5"), 
        horiz = T, xlab = "Number of cyclone generation centers")
```

```{r}
cyclones <- read.csv('C:/Users/usuario/Desktop/Master/tfm/Notebooks_TFM/SP_cyclones_time_series_1979_2020.csv')
cyclones$Date <- as.Date(cyclones$Date)
cyclones <- cyclones[,2:3]
```

```{r}
load("C:/Users/usuario/Desktop/TRMM-Calibration/Data/pca.projected2.RData")
pca.projected.matrix <- cbind(pca.projected$tp[[1]],pca.projected$msl[[1]],pca.projected$diff_slp[[1]])

```

```{r}
clustering <- cl_predict(kmModel5, pca.projected.matrix, type = "class_ids")
```

```{r}
clustering[1] <- 1

clustering <- c(kmModel5$cluster, clustering)
``` 

```{r}
cyclones.cl1 <- cyclones[which(clustering == 1),]
cyclones.cl2 <- cyclones[which(clustering == 2),]
cyclones.cl3 <- cyclones[which(clustering == 3),]
cyclones.cl4 <- cyclones[which(clustering == 4),]
cyclones.cl5 <- cyclones[which(clustering == 5),]
```

```{r}
cyc.year1 <- c()
cyc.year2 <- c()
cyc.year3 <- c()
cyc.year4 <- c()
cyc.year5 <- c()

for (i in seq(1979,2020)) {
  idx.cl1 <- which(year(cyclones.cl1$Date) == i)
  idx.cl2 <- which(year(cyclones.cl2$Date) == i)
  idx.cl3 <- which(year(cyclones.cl3$Date) == i)
  idx.cl4 <- which(year(cyclones.cl4$Date) == i)
  idx.cl5 <- which(year(cyclones.cl5$Date) == i)
  
  cyc.year1 <- c(cyc.year1,sum(cyclones.cl1$cyclones_generation_centers[idx.cl1]))
  cyc.year2 <- c(cyc.year2,sum(cyclones.cl2$cyclones_generation_centers[idx.cl2]))
  cyc.year3 <- c(cyc.year3,sum(cyclones.cl3$cyclones_generation_centers[idx.cl3]))
  cyc.year4 <- c(cyc.year4,sum(cyclones.cl4$cyclones_generation_centers[idx.cl4]))
  cyc.year5 <- c(cyc.year5,sum(cyclones.cl5$cyclones_generation_centers[idx.cl5]))
}
```



```{r}
barplot(rbind(cyc.year1, cyc.year2, cyc.year3, cyc.year4, cyc.year5),
        col = c("#006837","#66C2A5","#FFFFBF","#5E4FA2","#F46D43"), horiz = T,
        names.arg = seq(1979,2020,1), cex.names = .5, las = 2,
        ylab = "Annual cyclone generation centers")
```

