---
title: "Calibration composition conditioned to WT"
author: "Óscar Mirones Alonso"
output: 
  html_notebook:
    theme: united
    toc: yes
    toc_depth: 5
---

```{r eval=TRUE, message=FALSE}
library(loadeR)
library(transformeR)
library(downscaleR)
library(visualizeR)
library(convertR)
library(ncdf4)
library(climate4R.value)
library(magrittr)
library(evd)
library(formattable) #neccessary to create tables with colors
library(lubridate) #neccessary to calculate differences in years between dates
```
```{r}
set.seed(42)
```

```{r}
load("C:/Users/usuario/Desktop/TRMM-Calibration/Data/pp_reanalysis.RData")

```

```{r}
load("C:/Users/usuario/Desktop/TRMM-Calibration/Data/pca.RData")
```

```{r}
idx.tp <- which(attributes(pca$tp[[1]])$explained_variance >= .75)[1]
idx.msl <- which(attributes(pca$msl[[1]])$explained_variance >= .9)[1]
idx.diff.msl <- which(attributes(pca$diff_msl[[1]])$explained_variance >= .9)[1]

pca.matrix <- cbind(pca$tp[[1]]$PCs[,1:idx.tp],pca$msl[[1]]$PCs[,1:idx.msl],pca$diff_msl[[1]]$PCs[,1:idx.diff.msl])

```

```{r}
k = 5
load('C:/Users/usuario/Desktop/TRMM-Calibration/Data/kmModel5.RData')
```

```{r}
lista <- lapply(1:k, function(x) subsetDimension(pp_reanalysis, dimension = "time", indices = which(kmModel5$cluster == x)) %>% climatology())

kmedias.pp <- bindGrid(lista, dimension = "member", skip.temporal.check = TRUE)

spatialPlot(kmedias.pp,backdrop.theme = 'countries', rev.color = T, as.table = T, names.attr = paste("Days in cluster", 1:k, ":",kmModel5$size[1:k]))
```

```{r}
MaxReturnValue <- function(data){
  #library(lubridate)
  #nyears <- round(time_length(difftime(cal.madrid.eqm$Dates$end[length(cal.madrid.eqm$Dates$end)], cal.madrid.eqm$Dates$start[1]),"years"))
  nyears <- 20
  data.maxYear <- aggregateGrid(redim(data), aggr.y = list(FUN = "max",na.rm = TRUE))

  data.maxrv <- climatology(data, clim.fun = list(FUN = "mean", na.rm = T))

  auxData <- data.maxYear$Data
  auxData[which(is.infinite(auxData))] <- NA

  if (any(!is.na(auxData))){
      auxGEV <- fgev(auxData)
      if ((auxGEV$estimate[3] - auxGEV$std.err[3] < 0) & (0  < auxGEV$estimate[3] + auxGEV$std.err[3])){
        auxGEV <- fgev(auxData, shape = 0)
        auxRV <- qgev(1-1/nyears, loc = auxGEV$estimate[1], scale = auxGEV$estimate[2], shape = 0)
      }else{
        auxRV <- qgev(1-1/nyears, loc = auxGEV$estimate[1], scale = auxGEV$estimate[2], shape = auxGEV$estimate[3])
      }
      data.maxrv <- as.numeric(auxRV)
      names(data.maxrv) <- paste("RV",nyears,"_max", sep = "")
  }
  return(data.maxrv)
  }
```

```{r}
precip_obs <- loadStationData("C:/Users/usuario/Desktop/TRMM-Calibration/TRMM-time-series/WT_Analysis_Calibration/SP_ascii.zip", var = "precip_obs")

```

```{r}
precip_trmm <- loadStationData("C:/Users/usuario/Desktop/TRMM-Calibration/TRMM-time-series/WT_Analysis_Calibration/SP_ascii.zip", var = "precip_trmm")

```
```{r}
kmModel5$cluster <- kmModel5$cluster[1:8034]
```

```{r}
i=6

station.trmm <- subsetGrid(precip_trmm, station.id = precip_trmm$Metadata$station_id[i])
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])
```

```{r}
temporalPlot(station.obs,station.trmm, xyplot.custom = list(main = paste("Precipitation in",station.trmm$Metadata$name,"(elevation",precip_trmm$Metadata$altitude[i],"m)"), ylab = "mm"))
```

```{r}
index.obs <- valueIndex1D(station.obs$Data[!is.na(station.obs$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs <- c(index.obs, valueIndex1D(station.obs$Data[!is.na(station.obs$Data)], index.codes = "P98WetAmount"))
index.obs.rv20max <- MaxReturnValue(station.obs)

index.trmm <- valueIndex1D(station.trmm$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))
index.trmm.rv20max <- MaxReturnValue(station.trmm)


```

```{r}
index.obs <- c(index.obs, index.obs.rv20max)
index.trmm <- c(index.trmm, index.trmm.rv20max)
```

```{r}
station.obs.cl1 <- subsetDimension(station.obs, dimension = "time", indices = which(kmModel5$cluster == 1))
station.obs.cl2 <- subsetDimension(station.obs, dimension = "time", indices = which(kmModel5$cluster == 2))
station.obs.cl3 <- subsetDimension(station.obs, dimension = "time", indices = which(kmModel5$cluster == 3))
station.obs.cl4 <- subsetDimension(station.obs, dimension = "time", indices = which(kmModel5$cluster == 4))
station.obs.cl5 <- subsetDimension(station.obs, dimension = "time", indices = which(kmModel5$cluster == 5))
```

```{r}
station.trmm.cl1 <- subsetDimension(station.trmm, dimension = "time", indices = which(kmModel5$cluster == 1))
station.trmm.cl2 <- subsetDimension(station.trmm, dimension = "time", indices = which(kmModel5$cluster == 2))
station.trmm.cl3 <- subsetDimension(station.trmm, dimension = "time", indices = which(kmModel5$cluster == 3))
station.trmm.cl4 <- subsetDimension(station.trmm, dimension = "time", indices = which(kmModel5$cluster == 4))
station.trmm.cl5 <- subsetDimension(station.trmm, dimension = "time", indices = which(kmModel5$cluster == 5))
```

```{r}
index.obs.cl1 <- valueIndex1D(station.obs.cl1$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs.cl1 <- c(index.obs.cl1, valueIndex1D(station.obs.cl1$Data[!is.na(station.obs.cl1$Data)], index.codes = "P98WetAmount"))
index.obs.cl1.rv20max <- MaxReturnValue(station.obs.cl1)

index.trmm.cl1 <- valueIndex1D(station.trmm.cl1$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.trmm.cl1 <- c(index.trmm.cl1, valueIndex1D(station.trmm.cl1$Data[!is.na(station.trmm.cl1$Data)], index.codes = "P98WetAmount"))
index.trmm.cl1.rv20max <- MaxReturnValue(station.trmm.cl1)
```

```{r}
index.obs.cl1 <- c(index.obs.cl1, index.obs.cl1.rv20max)
index.trmm.cl1 <- c(index.trmm.cl1, index.trmm.cl1.rv20max)
```


```{r}
index.obs.cl2 <- valueIndex1D(station.obs.cl2$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs.cl2 <- c(index.obs.cl2, valueIndex1D(station.obs.cl2$Data[!is.na(station.obs.cl2$Data)], index.codes = "P98WetAmount"))
index.obs.cl2.rv20max <- MaxReturnValue(station.obs.cl2)

index.trmm.cl2 <- valueIndex1D(station.trmm.cl2$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.trmm.cl2 <- c(index.trmm.cl2, valueIndex1D(station.trmm.cl2$Data[!is.na(station.trmm.cl2$Data)], index.codes = "P98WetAmount"))
index.trmm.cl2.rv20max <- MaxReturnValue(station.trmm.cl2)
```

```{r}
index.obs.cl2 <- c(index.obs.cl2, index.obs.cl2.rv20max)
index.trmm.cl2<- c(index.trmm.cl2, index.trmm.cl2.rv20max)
```

```{r}
index.obs.cl3 <- valueIndex1D(station.obs.cl3$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs.cl3 <- c(index.obs.cl3, valueIndex1D(station.obs.cl3$Data[!is.na(station.obs.cl3$Data)], index.codes = "P98WetAmount"))
index.obs.cl3.rv20max <- MaxReturnValue(station.obs.cl3)

index.trmm.cl3 <- valueIndex1D(station.trmm.cl3$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.trmm.cl3 <- c(index.trmm.cl3, valueIndex1D(station.trmm.cl3$Data[!is.na(station.trmm.cl3$Data)], index.codes = "P98WetAmount"))
index.trmm.cl3.rv20max <- MaxReturnValue(station.trmm.cl3)
```

```{r}
index.obs.cl3 <- c(index.obs.cl3, index.obs.cl3.rv20max)
index.trmm.cl3 <- c(index.trmm.cl3, index.trmm.cl3.rv20max)
```

```{r}
index.obs.cl4 <- valueIndex1D(station.obs.cl4$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs.cl4 <- c(index.obs.cl4, valueIndex1D(station.obs.cl4$Data[!is.na(station.obs.cl4$Data)], index.codes = "P98WetAmount"))
index.obs.cl4.rv20max <- MaxReturnValue(station.obs.cl4)

index.trmm.cl4 <- valueIndex1D(station.trmm.cl4$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.trmm.cl4 <- c(index.trmm.cl4, valueIndex1D(station.trmm.cl4$Data[!is.na(station.trmm.cl4$Data)], index.codes = "P98WetAmount"))
index.trmm.cl4.rv20max <- MaxReturnValue(station.trmm.cl4)
```

```{r}
index.obs.cl4 <- c(index.obs.cl4, index.obs.cl4.rv20max)
index.trmm.cl4 <- c(index.trmm.cl4, index.trmm.cl4.rv20max)
```

```{r}
index.obs.cl5 <- valueIndex1D(station.obs.cl5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.obs.cl5 <- c(index.obs.cl5, valueIndex1D(station.obs.cl5$Data[!is.na(station.obs.cl5$Data)], index.codes = "P98WetAmount"))
index.obs.cl5.rv20max <- MaxReturnValue(station.obs.cl5)

index.trmm.cl5 <- valueIndex1D(station.trmm.cl5$Data,index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet"))
index.trmm.cl5 <- c(index.trmm.cl5, valueIndex1D(station.trmm.cl5$Data[!is.na(station.trmm.cl5$Data)], index.codes = "P98WetAmount"))
index.trmm.cl5.rv20max <- MaxReturnValue(station.trmm.cl5)
```

```{r}
index.obs.cl5 <- c(index.obs.cl5, index.obs.cl5.rv20max)
index.trmm.cl5 <- c(index.trmm.cl5, index.trmm.cl5.rv20max)
```

```{r eval= TRUE, message= FALSE}
cal.station.cl1.pqm <- biasCorrection(y = station.obs.cl1, x = station.trmm.cl1,
                                  precipitation = TRUE,  method = "pqm")
cal.station.cl1.eqm <-biasCorrection(y = station.obs.cl1, x = station.trmm.cl1,
                                  precipitation = TRUE,  method = "eqm")
cal.station.cl1.gpqm <-biasCorrection(y = station.obs.cl1, x = station.trmm.cl1,
                                  precipitation = TRUE,  method = "gpqm", theta = .95)
cal.station.cl1.gpqm2 <-biasCorrection(y = station.obs.cl1, x = station.trmm.cl1,
                                  precipitation = TRUE,  method = "gpqm", theta = .7)
```

```{r}
index.cal.station.cl1.pqm <- valueIndex1D(cal.station.cl1.pqm$Data[!is.na(cal.station.cl1.pqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl1.pqm.rv20max <- MaxReturnValue(cal.station.cl1.pqm)

index.cal.station.cl1.pqm <- c(index.cal.station.cl1.pqm, index.cal.station.cl1.pqm.rv20max)

```
```{r}
index.cal.station.cl1.eqm <- valueIndex1D(cal.station.cl1.eqm$Data[!is.na(cal.station.cl1.eqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl1.eqm.rv20max <- MaxReturnValue(cal.station.cl1.eqm)

index.cal.station.cl1.eqm <- c(index.cal.station.cl1.eqm, index.cal.station.cl1.eqm.rv20max)

```
```{r}
index.cal.station.cl1.gpqm <- valueIndex1D(cal.station.cl1.gpqm$Data[!is.na(cal.station.cl1.gpqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl1.gpqm.rv20max <- MaxReturnValue(cal.station.cl1.gpqm)

index.cal.station.cl1.gpqm <- c(index.cal.station.cl1.gpqm, index.cal.station.cl1.gpqm.rv20max)

```
```{r}
index.cal.station.cl1.gpqm2 <- valueIndex1D(cal.station.cl1.gpqm2$Data[!is.na(cal.station.cl1.gpqm2$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl1.gpqm2.rv20max <- MaxReturnValue(cal.station.cl1.gpqm2)

index.cal.station.cl1.gpqm2 <- c(index.cal.station.cl1.gpqm2, index.cal.station.cl1.gpqm2.rv20max)

```

```{r}
df <- data.frame(index.obs.cl1, index.trmm.cl1-index.obs.cl1, index.cal.station.cl1.pqm-index.obs.cl1, index.cal.station.cl1.eqm-index.obs.cl1, index.cal.station.cl1.gpqm-index.obs.cl1, index.cal.station.cl1.gpqm2-index.obs.cl1)
colnames(df) <- c("Obs WT1","TRMM WT1","PQM WT1", "EQM WT1", "GPQM WT1", "GPQM2 WT1")
format(df, digits = 3, scientific = 5)
```


```{r eval= TRUE, message= FALSE}
cal.station.cl2.pqm <- biasCorrection(y = station.obs.cl2, x = station.trmm.cl2,
                                  precipitation = TRUE,  method = "pqm")
cal.station.cl2.eqm <-biasCorrection(y = station.obs.cl2, x = station.trmm.cl2,
                                  precipitation = TRUE,  method = "eqm")
cal.station.cl2.gpqm <-biasCorrection(y = station.obs.cl2, x = station.trmm.cl2,
                                  precipitation = TRUE,  method = "gpqm", theta = .95)
cal.station.cl2.gpqm2 <-biasCorrection(y = station.obs.cl2, x = station.trmm.cl2,
                                  precipitation = TRUE,  method = "gpqm", theta = .7)
```

```{r}
index.cal.station.cl2.pqm <- valueIndex1D(cal.station.cl2.pqm$Data[!is.na(cal.station.cl2.pqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl2.pqm.rv20max <- MaxReturnValue(cal.station.cl2.pqm)

index.cal.station.cl2.pqm <- c(index.cal.station.cl2.pqm, index.cal.station.cl2.pqm.rv20max)

```
```{r}
index.cal.station.cl2.eqm <- valueIndex1D(cal.station.cl2.eqm$Data[!is.na(cal.station.cl2.eqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl2.eqm.rv20max <- MaxReturnValue(cal.station.cl2.eqm)

index.cal.station.cl2.eqm <- c(index.cal.station.cl2.eqm, index.cal.station.cl2.eqm.rv20max)

```
```{r}
index.cal.station.cl2.gpqm <- valueIndex1D(cal.station.cl2.gpqm$Data[!is.na(cal.station.cl2.gpqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl2.gpqm.rv20max <- MaxReturnValue(cal.station.cl2.gpqm)

index.cal.station.cl2.gpqm <- c(index.cal.station.cl2.gpqm, index.cal.station.cl2.gpqm.rv20max)

```
```{r}
index.cal.station.cl2.gpqm2 <- valueIndex1D(cal.station.cl2.gpqm2$Data[!is.na(cal.station.cl2.gpqm2$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl2.gpqm2.rv20max <- MaxReturnValue(cal.station.cl2.gpqm2)

index.cal.station.cl2.gpqm2 <- c(index.cal.station.cl2.gpqm2, index.cal.station.cl2.gpqm2.rv20max)

```

```{r}
df <- data.frame(index.obs.cl2, index.trmm.cl2-index.obs.cl2, index.cal.station.cl2.pqm-index.obs.cl2, index.cal.station.cl2.eqm-index.obs.cl2, index.cal.station.cl2.gpqm-index.obs.cl2, index.cal.station.cl2.gpqm2-index.obs.cl2)
colnames(df) <- c("Obs WT2","TRMM WT2","PQM WT2", "EQM WT2", "GPQM WT2", "GPQM2 WT2")
format(df, digits = 3, scientific = 5)
```
```{r eval= TRUE, message= FALSE}
cal.station.cl3.pqm <- biasCorrection(y = station.obs.cl3, x = station.trmm.cl3,
                                  precipitation = TRUE,  method = "pqm")
cal.station.cl3.eqm <-biasCorrection(y = station.obs.cl3, x = station.trmm.cl3,
                                  precipitation = TRUE,  method = "eqm")
cal.station.cl3.gpqm <-biasCorrection(y = station.obs.cl3, x = station.trmm.cl3,
                                  precipitation = TRUE,  method = "gpqm", theta = .95)
cal.station.cl3.gpqm2 <-biasCorrection(y = station.obs.cl3, x = station.trmm.cl3,
                                  precipitation = TRUE,  method = "gpqm", theta = .7)
```

```{r}
index.cal.station.cl3.pqm <- valueIndex1D(cal.station.cl3.pqm$Data[!is.na(cal.station.cl3.pqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl3.pqm.rv20max <- MaxReturnValue(cal.station.cl3.pqm)

index.cal.station.cl3.pqm <- c(index.cal.station.cl3.pqm, index.cal.station.cl3.pqm.rv20max)

```
```{r}
index.cal.station.cl3.eqm <- valueIndex1D(cal.station.cl3.eqm$Data[!is.na(cal.station.cl3.eqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl3.eqm.rv20max <- MaxReturnValue(cal.station.cl3.eqm)

index.cal.station.cl3.eqm <- c(index.cal.station.cl3.eqm, index.cal.station.cl3.eqm.rv20max)

```
```{r}
index.cal.station.cl3.gpqm <- valueIndex1D(cal.station.cl3.gpqm$Data[!is.na(cal.station.cl3.gpqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl3.gpqm.rv20max <- MaxReturnValue(cal.station.cl3.gpqm)

index.cal.station.cl3.gpqm <- c(index.cal.station.cl3.gpqm, index.cal.station.cl3.gpqm.rv20max)

```
```{r}
index.cal.station.cl3.gpqm2 <- valueIndex1D(cal.station.cl3.gpqm2$Data[!is.na(cal.station.cl3.gpqm2$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl3.gpqm2.rv20max <- MaxReturnValue(cal.station.cl3.gpqm2)

index.cal.station.cl3.gpqm2 <- c(index.cal.station.cl3.gpqm2, index.cal.station.cl3.gpqm2.rv20max)

```

```{r}
df <- data.frame(index.obs.cl3, index.trmm.cl3-index.obs.cl3, index.cal.station.cl3.pqm-index.obs.cl3, index.cal.station.cl3.eqm-index.obs.cl3, index.cal.station.cl3.gpqm-index.obs.cl3, index.cal.station.cl3.gpqm2-index.obs.cl3)
colnames(df) <- c("Obs WT3","TRMM WT3","PQM WT3", "EQM WT3", "GPQM WT3", "GPQM2 WT3")
format(df, digits = 3, scientific = 5)
```
```{r eval= TRUE, message= FALSE}
cal.station.cl4.pqm <- biasCorrection(y = station.obs.cl4, x = station.trmm.cl4,
                                  precipitation = TRUE,  method = "pqm")
cal.station.cl4.eqm <-biasCorrection(y = station.obs.cl4, x = station.trmm.cl4,
                                  precipitation = TRUE,  method = "eqm")
cal.station.cl4.gpqm <-biasCorrection(y = station.obs.cl4, x = station.trmm.cl4,
                                 precipitation = TRUE,  method = "gpqm", theta = .95)
cal.station.cl4.gpqm2 <-biasCorrection(y = station.obs.cl4, x = station.trmm.cl4,
                                  precipitation = TRUE,  method = "gpqm", theta = .7)
```
```{r}
index.cal.station.cl4.pqm <- valueIndex1D(cal.station.cl4.pqm$Data[!is.na(cal.station.cl4.pqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl4.pqm.rv20max <- MaxReturnValue(cal.station.cl4.pqm)

index.cal.station.cl4.pqm <- c(index.cal.station.cl4.pqm, index.cal.station.cl4.pqm.rv20max)

```
```{r}
index.cal.station.cl4.eqm <- valueIndex1D(cal.station.cl4.eqm$Data[!is.na(cal.station.cl4.eqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl4.eqm.rv20max <- MaxReturnValue(cal.station.cl4.eqm)

index.cal.station.cl4.eqm <- c(index.cal.station.cl4.eqm, index.cal.station.cl4.eqm.rv20max)

```
```{r}
index.cal.station.cl4.gpqm <- valueIndex1D(cal.station.cl4.gpqm$Data[!is.na(cal.station.cl4.gpqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl4.gpqm.rv20max <- MaxReturnValue(cal.station.cl4.gpqm)

index.cal.station.cl4.gpqm <- c(index.cal.station.cl4.gpqm, index.cal.station.cl4.gpqm.rv20max)

```
```{r}
index.cal.station.cl4.gpqm2 <- valueIndex1D(cal.station.cl4.gpqm2$Data[!is.na(cal.station.cl4.gpqm2$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl4.gpqm2.rv20max <- MaxReturnValue(cal.station.cl4.gpqm2)

index.cal.station.cl4.gpqm2 <- c(index.cal.station.cl4.gpqm2, index.cal.station.cl4.gpqm2.rv20max)

```

```{r}
df <- data.frame(index.obs.cl4, index.trmm.cl4-index.obs.cl4, index.cal.station.cl4.pqm-index.obs.cl4, index.cal.station.cl4.eqm-index.obs.cl4, index.cal.station.cl4.gpqm-index.obs.cl4, index.cal.station.cl4.gpqm2-index.obs.cl4)
colnames(df) <- c("Obs WT4","TRMM WT4","PQM WT4", "EQM WT4", "GPQM WT4", "GPQM2 WT4")
format(df, digits = 3, scientific = 5)
```
```{r eval= TRUE, message= FALSE}
cal.station.cl5.pqm <- biasCorrection(y = station.obs.cl5, x = station.trmm.cl5,
                                  precipitation = TRUE,  method = "pqm")
cal.station.cl5.eqm <-biasCorrection(y = station.obs.cl5, x = station.trmm.cl5,
                                  precipitation = TRUE,  method = "eqm")
cal.station.cl5.gpqm <-biasCorrection(y = station.obs.cl5, x = station.trmm.cl5,
                                  precipitation = TRUE,  method = "gpqm", theta = .95)
cal.station.cl5.gpqm2 <-biasCorrection(y = station.obs.cl5, x = station.trmm.cl5,
                                  precipitation = TRUE,  method = "gpqm", theta = .7)
```
```{r}
index.cal.station.cl5.pqm <- valueIndex1D(cal.station.cl5.pqm$Data[!is.na(cal.station.cl5.pqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl5.pqm.rv20max <- MaxReturnValue(cal.station.cl5.pqm)

index.cal.station.cl5.pqm <- c(index.cal.station.cl5.pqm, index.cal.station.cl5.pqm.rv20max)

```
```{r}
index.cal.station.cl5.eqm <- valueIndex1D(cal.station.cl5.eqm$Data[!is.na(cal.station.cl5.eqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl5.eqm.rv20max <- MaxReturnValue(cal.station.cl5.eqm)

index.cal.station.cl5.eqm <- c(index.cal.station.cl5.eqm, index.cal.station.cl5.eqm.rv20max)

```
```{r}
index.cal.station.cl5.gpqm <- valueIndex1D(cal.station.cl5.gpqm$Data[!is.na(cal.station.cl5.gpqm$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl5.gpqm.rv20max <- MaxReturnValue(cal.station.cl5.gpqm)

index.cal.station.cl5.gpqm <- c(index.cal.station.cl5.gpqm, index.cal.station.cl5.gpqm.rv20max)

```
```{r}
index.cal.station.cl5.gpqm2 <- valueIndex1D(cal.station.cl5.gpqm2$Data[!is.na(cal.station.cl5.gpqm2$Data)],index.codes=c("Skewness","SDII","R10","R10p","R20","R20p","P98Wet","P98WetAmount"))


index.cal.station.cl5.gpqm2.rv20max <- MaxReturnValue(cal.station.cl5.gpqm2)

index.cal.station.cl5.gpqm2 <- c(index.cal.station.cl5.gpqm2, index.cal.station.cl5.gpqm2.rv20max)

```

```{r}
df <- data.frame(index.obs.cl5, index.trmm.cl5-index.obs.cl5, index.cal.station.cl5.pqm-index.obs.cl5, index.cal.station.cl5.eqm-index.obs.cl5, index.cal.station.cl5.gpqm-index.obs.cl5, index.cal.station.cl5.gpqm2-index.obs.cl5)
colnames(df) <- c("Obs WT5","TRMM WT5","PQM WT5", "EQM WT5", "GPQM WT5", "GPQM2 WT5")
format(df, digits = 3, scientific = 5)
```


```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.pqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.pqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination1 <- wt_conditioned
```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 1","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```
```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.pqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.pqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination2 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 2","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.eqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.pqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination3 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 3","TRMM"), pch = c(2,4), col = c("black", "red"))

grid()  
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.eqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.pqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination4 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 4","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.gpqm2, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.pqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination5 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 5","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.gpqm2, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.pqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination6 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 6","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.pqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.eqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination7 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 7","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.pqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.eqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination8 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 8","TRMM"), pch = c(2,4), col = c("black", "red"))

grid()  
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.eqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.eqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination9 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 9","TRMM"), pch = c(2,4), col = c("black", "red"))

grid()  
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.eqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.eqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination10 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 10","TRMM"), pch = c(2,4), col = c("black", "red"))

grid()  
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.gpqm2, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.eqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination11 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 11","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.gpqm2, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.eqm, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination12 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 12","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```
```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.pqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.gpqm2, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination13 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 13","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.pqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.gpqm2, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination14 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 14","TRMM"), pch = c(2,4), col = c("black", "red"))

grid()  
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.eqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.gpqm2, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination15 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 15","TRMM"), pch = c(2,4), col = c("black", "red"))

grid()  
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.eqm, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.gpqm2, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination16 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 16","TRMM"), pch = c(2,4), col = c("black", "red"))

grid()  
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.eqm, cal.station.cl2.gpqm2, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.gpqm2, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination17 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 17","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```

```{r}
wt_conditioned <- bindGrid(cal.station.cl1.gpqm2, cal.station.cl2.gpqm2, cal.station.cl3.pqm,
                           cal.station.cl4.pqm, cal.station.cl5.gpqm2, dimension = "time")

wt_conditioned$Data <- wt_conditioned$Data[!is.na(wt_conditioned$Data)]
wt_conditioned$Dates$start <- unique(wt_conditioned$Dates$start)
wt_conditioned$Dates$end <- unique(wt_conditioned$Dates$end)

combination18 <- wt_conditioned

```


```{r}
qqplot(station.obs$Data, wt_conditioned$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), sort(station.trmm$Data[!is.na(station.obs$Data)][-1]), col = "red", pch = 4, cex = .5)

legend("topleft", legend = c("Combinated 18","TRMM"), pch = c(2,4), col = c("black", "red"))

grid() 
```


```{r}
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])


idx <- which(!is.na(station.obs$Data))

combination1$Data <- combination1$Data[idx]

good <- !is.na(combination1$Data)
ord <- order(combination1$Data[good])
ord.x <- combination1$Data[good][ord]
combination1$Data <- ord.x

combination2$Data <- combination2$Data[idx]

good <- !is.na(combination2$Data)
ord <- order(combination2$Data[good])
ord.x <- combination2$Data[good][ord]
combination2$Data <- ord.x

combination3$Data <- combination3$Data[idx]

good <- !is.na(combination3$Data)
ord <- order(combination3$Data[good])
ord.x <- combination3$Data[good][ord]
combination3$Data <- ord.x

combination4$Data <- combination4$Data[idx]

good <- !is.na(combination4$Data)
ord <- order(combination4$Data[good])
ord.x <- combination4$Data[good][ord]
combination4$Data <- ord.x

combination5$Data <- combination5$Data[idx]

good <- !is.na(combination5$Data)
ord <- order(combination5$Data[good])
ord.x <- combination5$Data[good][ord]
combination5$Data <- ord.x

combination6$Data <- combination6$Data[idx]

good <- !is.na(combination6$Data)
ord <- order(combination6$Data[good])
ord.x <- combination6$Data[good][ord]
combination6$Data <- ord.x
```


```{r}
qqplot(station.obs$Data, combination1$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim =  c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,6), combination2$Data), col = "red", pch = 3, cex = .5)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,4),combination3$Data), col = "pink", pch = 3, cex = .5)
 
points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,4), combination4$Data), col = "blue", pch = 2, cex = .5)
 
points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,4),combination5$Data), col = "green", pch = 2, cex = .5)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,4), combination6$Data), col = "gold", pch = 3, cex = .5)

legend("topleft", legend = c("C1","C2","C3","C4","C5","C6"), pch = c(2,3,3,2,2,3), col = c("black", "red","pink","blue","green","gold"))

grid() 
```


```{r}
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])


idx <- which(!is.na(station.obs$Data))

combination8$Data <- combination8$Data[idx]

good <- !is.na(combination8$Data)
ord <- order(combination8$Data[good])
ord.x <- combination8$Data[good][ord]
combination8$Data <- ord.x

combination9$Data <- combination9$Data[idx]

good <- !is.na(combination9$Data)
ord <- order(combination9$Data[good])
ord.x <- combination9$Data[good][ord]
combination9$Data <- ord.x

combination10$Data <- combination10$Data[idx]

good <- !is.na(combination10$Data)
ord <- order(combination10$Data[good])
ord.x <- combination10$Data[good][ord]
combination10$Data <- ord.x

combination11$Data <- combination11$Data[idx]

good <- !is.na(combination11$Data)
ord <- order(combination11$Data[good])
ord.x <- combination11$Data[good][ord]
combination11$Data <- ord.x

combination12$Data <- combination12$Data[idx]

good <- !is.na(combination12$Data)
ord <- order(combination12$Data[good])
ord.x <- combination12$Data[good][ord]
combination12$Data <- ord.x
```



```{r}
qqplot(station.obs$Data, combination7$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5,ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,3), combination8$Data), col = "red", pch = 3, cex = .5)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2),combination9$Data), col = "pink", pch = 3, cex = .5)
 
points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2), combination10$Data), col = "blue", pch = 2, cex = .5)
 
points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2),combination11$Data), col = "green", pch = 2, cex = .5)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2), combination12$Data), col = "gold", pch = 3, cex = .5)

legend("topleft", legend = c("C7","C8","C9","C10","C11","C12"), pch = c(2,3,3,2,2,3), col = c("black", "red","pink","blue","green","gold"))

grid() 
```

```{r}
station.obs <- subsetGrid(precip_obs, station.id = precip_trmm$Metadata$station_id[i])


idx <- which(!is.na(station.obs$Data))

combination13$Data <- combination13$Data[idx]

good <- !is.na(combination13$Data)
ord <- order(combination13$Data[good])
ord.x <- combination13$Data[good][ord]
combination13$Data <- ord.x

combination14$Data <- combination14$Data[idx]

good <- !is.na(combination14$Data)
ord <- order(combination14$Data[good])
ord.x <- combination14$Data[good][ord]
combination14$Data <- ord.x

combination15$Data <- combination15$Data[idx]

good <- !is.na(combination15$Data)
ord <- order(combination15$Data[good])
ord.x <- combination15$Data[good][ord]
combination15$Data <- ord.x

combination16$Data <- combination16$Data[idx]

good <- !is.na(combination16$Data)
ord <- order(combination16$Data[good])
ord.x <- combination16$Data[good][ord]
combination16$Data <- ord.x

combination17$Data <- combination17$Data[idx]

good <- !is.na(combination17$Data)
ord <- order(combination17$Data[good])
ord.x <- combination17$Data[good][ord]
combination17$Data <- ord.x

combination18$Data <- combination18$Data[idx]

good <- !is.na(combination18$Data)
ord <- order(combination18$Data[good])
ord.x <- combination18$Data[good][ord]
combination18$Data <- ord.x
```


```{r}
qqplot(station.obs$Data, combination13$Data, main = paste(station.obs$Metadata$name), xlab = "Observed (mm)", ylab = "Predicted (mm)", col = "black", pch = 2, cex = .5, ylim = c(0,550))

abline(a = 0, b = 1)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,3), combination14$Data), col = "red", pch = 3, cex = .5)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2),combination15$Data), col = "pink", pch = 3, cex = .5)
 
points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2), combination16$Data), col = "blue", pch = 2, cex = .5)
 
points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2),combination17$Data), col = "green", pch = 2, cex = .5)

points(sort(station.obs$Data[!is.na(station.obs$Data)]), c(rep(0,2), combination18$Data), col = "gold", pch = 3, cex = .5)

legend("topleft", legend = c("C13","C14","C15","C16","C17","C18"), pch = c(2,3,3,2,2,3), col = c("black", "red","pink","blue","green","gold"))

grid() 
```